INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'TD_DISC_PACK', '812e1be6-bfa2-4c28-84c9-73e8c6273b0d', 'TD Ameritrade Institutional Disclosure Packet', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK', '9ffbe9b5-ba2d-485a-a56b-267b7cc6fb6c', 'AdvisorDirect Disclosure Brochure, Rev. April 10, 2017', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'MARGIN_AGREE', 'b628948e-6ab6-4394-929b-2033dab01dc6', 'Margin Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'PRIM_BROK_AGREE', '081d7bf2-30f1-4b3d-a2af-55b706455c20', 'Prime Brokerage Services Agreement Amendment', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'IRA_CUST_AGREE', 'a506850a-1ea0-41af-b305-d081e08efe2f', 'IRA Custodial Account Agreement- Mandatory for new client IRA accounts', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'IRA_DIST_HOLD_FORM', 'd76d6acd-5e6e-4607-b033-571e08e498ef', 'TEMPLATE NAME', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK2', '9ffbe9b5-ba2d-485a-a56b-267b7cc6fb6c', 'AdvisorDirect Disclosure Brochure, Rev. April 10, 2017', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'TCM_DIRECT_AGREE', '1111', 'TEMPLATE NAME', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'TD_ADV_DIRECT_AGREE', '6cbac72a-e206-43e8-b20d-3d19f9830742', 'TCM - TDAD Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'TCM', 'DOCUSIGN-SERVICES', 'TCM_THIRED_PARTY_DISC', '1111', 'TEMPLATE NAME', 'Y', 'A');

INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TD_DISC_PACK', '812e1be6-bfa2-4c28-84c9-73e8c6273b0d', 'TD Ameritrade Institutional Disclosure Packet', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK', '9ffbe9b5-ba2d-485a-a56b-267b7cc6fb6c', 'AdvisorDirect Disclosure Brochure, Rev. April 10, 2017', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'MARGIN_AGREE', 'b628948e-6ab6-4394-929b-2033dab01dc6', 'Margin Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'PRIM_BROK_AGREE', '081d7bf2-30f1-4b3d-a2af-55b706455c20', 'Prime Brokerage Services Agreement Amendment', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'IRA_CUST_AGREE', 'a506850a-1ea0-41af-b305-d081e08efe2f', 'IRA Custodial Account Agreement- Mandatory for new client IRA accounts', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'IRA_DIST_HOLD_FORM', 'd76d6acd-5e6e-4607-b033-571e08e498ef', 'TEMPLATE NAME', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK2', '9ffbe9b5-ba2d-485a-a56b-267b7cc6fb6c', 'AdvisorDirect Disclosure Brochure, Rev. April 10, 2017', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TCM_DIRECT_AGREE', '1111', 'TEMPLATE NAME', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TD_ADV_DIRECT_AGREE', '6cbac72a-e206-43e8-b20d-3d19f9830742', 'TCM - TDAD Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('PROD', 'BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TCM_THIRED_PARTY_DISC', '1111', 'TEMPLATE NAME', 'Y', 'A');









INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TD_DISC_PACK', 'DOCUSIGN', 'A', '0', 'TD_DISC_PACK');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK', 'DOCUSIGN', 'A', '0', 'ADV_DIRECT_DISC_BOOK');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'MARGIN_AGREE', 'DOCUSIGN', 'A', '0', 'MARGIN_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'PRIM_BROK_AGREE', 'DOCUSIGN', 'A', '0', 'PRIM_BROK_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'IRA_CUST_AGREE', 'DOCUSIGN', 'A', '0', 'IRA_CUST_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'IRA_DIST_HOLD_FORM', 'DOCUSIGN', 'A', '0', 'IRA_DIST_HOLD_FORM');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK2', 'DOCUSIGN', 'A', '0', 'ADV_DIRECT_DISC_BOOK2');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TCM_DIRECT_AGREE', 'DOCUSIGN', 'A', '0', 'TCM_DIRECT_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TD_ADV_DIRECT_AGREE', 'DOCUSIGN', 'A', '0', 'TD_ADV_DIRECT_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('BUILDINGBENJAMINS', 'DOCUSIGN-SERVICES', 'TCM_THIRED_PARTY_DISC', 'DOCUSIGN', 'A', '0', 'TCM_THIRED_PARTY_DISC');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'TD_DISC_PACK', 'DOCUSIGN', 'A', '0', 'TD_DISC_PACK');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK', 'DOCUSIGN', 'A', '0', 'ADV_DIRECT_DISC_BOOK');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'MARGIN_AGREE', 'DOCUSIGN', 'A', '0', 'MARGIN_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'PRIM_BROK_AGREE', 'DOCUSIGN', 'A', '0', 'PRIM_BROK_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'IRA_CUST_AGREE', 'DOCUSIGN', 'A', '0', 'IRA_CUST_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'IRA_DIST_HOLD_FORM', 'DOCUSIGN', 'A', '0', 'IRA_DIST_HOLD_FORM');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK2', 'DOCUSIGN', 'A', '0', 'ADV_DIRECT_DISC_BOOK2');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'TCM_DIRECT_AGREE', 'DOCUSIGN', 'A', '0', 'TCM_DIRECT_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'TD_ADV_DIRECT_AGREE', 'DOCUSIGN', 'A', '0', 'TD_ADV_DIRECT_AGREE');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `priority`, `refValue`) VALUES ('TCM', 'DOCUSIGN-SERVICES', 'TCM_THIRED_PARTY_DISC', 'DOCUSIGN', 'A', '0', 'TCM_THIRED_PARTY_DISC');










INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_DISC_PACK', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_DISC_PACK', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_DISC_PACK', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('MARGIN_AGREE', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('MARGIN_AGREE', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('MARGIN_AGREE', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('PRIM_BROK_AGREE', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('PRIM_BROK_AGREE', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('PRIM_BROK_AGREE', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_CUST_AGREE', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_CUST_AGREE', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_CUST_AGREE', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_DIST_HOLD_FORM', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_DIST_HOLD_FORM', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('IRA_DIST_HOLD_FORM', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK2', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK2', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('ADV_DIRECT_DISC_BOOK2', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_DIRECT_AGREE', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_DIRECT_AGREE', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_DIRECT_AGREE', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_ADV_DIRECT_AGREE', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_ADV_DIRECT_AGREE', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TD_ADV_DIRECT_AGREE', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_THIRED_PARTY_DISC', 'Textbox', 'AdvisorName', 'firmName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_THIRED_PARTY_DISC', 'Textbox', 'FullName', 'fullName', 'Client', 'N');
INSERT INTO `service`.`dc_template_mapping` (`tempCode`, `tab`, `lable`, `dbColumn`, `role`, `isDisabled`) VALUES ('TCM_THIRED_PARTY_DISC', 'Textbox', 'JointAHFullName', 'fullName', 'Joint', 'N');








delete from `invdb`.`adv_request_document_mappings`;

INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACAT2', 'ACAT_OTHER_NEW', 'Please sign account transfer document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACAT2', 'EXT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACAT2', 'INT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACAT2', 'INT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'ACCT_APPLI_NEW', 'Please sign Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACCT_APP_NEW', 'ACCT_APPLI_NEW', 'Please sign Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'ACCT_APPLI_NEW', 'Please sign Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACCT_APP_NEW', 'ACCT_APPLI_NEW', 'Please sign Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'MARGIN_AGREE', 'Please sign Account Application document.', '5', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'MARGIN_AGREE', 'Please sign Account Application document.', '5', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACCT_APP_NEW', 'MARGIN_AGREE', 'Please sign Account Application document.', '5', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '2', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACCT_APP_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '2', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACCT_APP_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '2', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '4', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '4', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '4', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '4', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'ACH_IRA', 'IRA_MOVE_MONEY_NEW', 'Please sign move money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'ACH_IRA', 'IRA_MOVE_MONEY_NEW', 'Please sign move money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'ACH_IRA', 'IRA_MOVE_MONEY_NEW', 'Please sign move money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'ACH_IRA', 'IRA_MOVE_MONEY_NEW', 'Please sign move money document.', '3', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'DEFAULT', 'ADV_DIRECT_DISC_BOOK', 'Please sign Account Application document.', '2', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'DEFAULT', 'BB_TCM_ADV_AGREE', 'Please sign account opening document.', '2', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'DEFAULT', 'TCM_ADV_2AB', 'Please sign account opening document.', '98', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'DEFAULT', 'TCM_ADV_2AB', 'Please sign account opening document.', '98', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'DEFAULT', 'TCM_ADV_2AB', 'Please sign account opening document.', '98', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'DEFAULT', 'TCM_ADV_2AB', 'Please sign account opening document.', '98', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'DEFAULT', 'TCM_PRIVACY_NOTICE', 'Please sign account opening document.', '99', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'DEFAULT', 'TCM_PRIVACY_NOTICE', 'Please sign account opening document.', '99', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'DEFAULT', 'TCM_PRIVACY_NOTICE', 'Please sign account opening document.', '99', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'DEFAULT', 'TCM_PRIVACY_NOTICE', 'Please sign account opening document.', '99', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'DEFAULT', 'TD_ADV_DIRECT_AGREE', 'Please sign Account Application document.', '4', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'DEFAULT', 'TD_DISC_PACK', 'Please sign Account Application document.', '1', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'DEFAULT', 'TD_DISC_PACK', 'Please sign Account Application document.', '1', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'DEFAULT', 'TD_DISC_PACK', 'Please sign Account Application document.', '1', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'DEFAULT', 'TD_DISC_PACK', 'Please sign Account Application document.', '1', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_APPLI_NEW', 'Please sign IRA Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_NEW', 'IRA_APPLI_NEW', 'Please sign IRA Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_APPLI_NEW', 'Please sign IRA Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_NEW', 'IRA_APPLI_NEW', 'Please sign IRA Account Application document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_NEW', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_NEW', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_NEW', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_NEW', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_NEW', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_NEW', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_CUST_AGREE', 'Please sign Account Application document.', '11', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_DIST_HOLD_FORM', 'Please sign Account Application document.', '13', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_QRP_BENE_NEW', 'Please sign account opening document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_QRP_BENE_NEW', 'Please sign account opening document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_QRP_BENE_NEW', 'Please sign account opening document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_QRP_BEN', 'IRA_QRP_BENE_NEW', 'Please sign account opening document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'IRA_QRP_BEN', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'IRA_QRP_BEN', 'PRIM_BROK_AGREE', 'Please sign Account Application document.', '12', 'ADV');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '5', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '5', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '5', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '5', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'ACCT_OPEN', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'ACCT_OPEN', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'ACCT_OPEN', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'ACCT_OPEN', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'CHNG_ADDR', 'CHNG_ADDR', 'ACCT_CHNG_ADDR', 'Please sign change address document.', '1000', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'CHNG_ADDR', 'CHNG_ADDR', 'ACCT_CHNG_ADDR', 'Please sign change address document.', '1000', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'CHNG_ADDR', 'CHNG_ADDR', 'ACCT_CHNG_ADDR', 'Please sign change address document.', '1000', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'CHNG_ADDR', 'CHNG_ADDR', 'ACCT_CHNG_ADDR', 'Please sign change address document.', '1000', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'ACAT', 'ACCT_TRAN_NEW', 'Please sign Agreement document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'ACAT2', 'ACAT_OTHER_NEW', 'Please sign account transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'ACAT2', 'EXT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'ACAT2', 'INT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'ACAT2', 'INT_ACAT_OTHER_NEW', 'Please sign account transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'ACH', 'MOVE_MONEY_NEW', 'Please sign Move Money document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'ACH_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '2', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'REC_EFT', 'ELEC_FUND_TRAN_NEW', 'Please sign Electric Fund Transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Advisor Direct', 'FUNDING', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('BB', 'FUNDING', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('Direct', 'FUNDING', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '1', 'DC');
INSERT INTO `invdb`.`adv_request_document_mappings` (`templateId`, `action`, `subaction`, `reqType`, `envelopeHeading`, `seqno`, `formType`) VALUES ('External', 'FUNDING', 'TDTRF', 'TD_TRAN_NEW', 'Please sign TD transfer document.', '1', 'DC');


/*'External', 'ACCT_OPEN', 'DEFAULT', 'TCM_THIRED_PARTY_DISC', 'Please sign Account Application document.', '4', 'ADV'
'Direct', 'ACCT_OPEN', 'DEFAULT', 'TCM_DIRECT_AGREE', 'Please sign Account Application document.', '4', 'ADV'
*/
