/**
 * AccountServicesSoap_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ws.gemini.wsdl.account;

public interface AccountServicesSoap_PortType extends java.rmi.Remote {
    public com.ws.gemini.wsdl.account.AccountInfoResult getAccountInfo(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, boolean isShareholder) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.MailingAddressesResult getMailingAddress(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, org.apache.axis.types.UnsignedByte mailingAddressType, org.apache.axis.types.UnsignedByte useRegistrationAddress, boolean isShareholder) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Beneficiary529Result getBeneficiary529(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, boolean isShareholder) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Plan529AccountBalanceActivityCollectionResult getPlan529AccountBalanceActivityCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, java.lang.String beneficiarySSN, int holidayListId, boolean isShareholder) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.ActivityCollectionResult getActivityCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, short fundId, java.util.Calendar valuationDate, java.util.Calendar valuationBeginDate, boolean isShareholder) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AuthorizedAccountCollectionResult getAuthorizedAccountCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AccountResult getAccount(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AuthorizedAccountsResult isAccountClosed(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Plan529AccountBalanceSummaryCollectionResult getPlan529AccountBalanceSummaryCollectionForAccount(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Plan529AccountBalanceSummaryCollectionResult getPlan529AccountBalanceSummaryCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, java.util.Calendar valuationDate) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.BalanceCollectionResult getBalanceCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, short fundId, java.util.Calendar valuationDate) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.BalanceCollectionResult getBalanceCollectionWithDateRange(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, short fundId, java.util.Calendar valuationDate, org.apache.axis.types.UnsignedByte displayCurrencyId, java.util.Calendar valuationBeginDate, org.apache.axis.types.UnsignedByte computeShareAmounts, org.apache.axis.types.UnsignedByte computePeriodDistributions, org.apache.axis.types.UnsignedByte computeDividendPayable, org.apache.axis.types.UnsignedByte computeAverageCostBasis, org.apache.axis.types.UnsignedByte computeReinvestmentSettings, org.apache.axis.types.UnsignedByte computeActivitySummary, org.apache.axis.types.UnsignedByte returnAllLinkedAccounts, org.apache.axis.types.UnsignedByte returnZeroBalanceSubAccounts, org.apache.axis.types.UnsignedByte valuationPriceCycleId, org.apache.axis.types.UnsignedByte valuationBeginPriceCycleId) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AchPayeeResult isAccountPayeeBeingUsed(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, org.apache.axis.types.UnsignedByte accountPayeeId) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AchPayeeCollectionResult getAchPayeeCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addAchPayee(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AchPayeeRequest achPayee) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status deleteAchPayee(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, org.apache.axis.types.UnsignedByte accountPayeeId, int achpayeeId) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.CheckWirePayeeCollectionResult getCheckWirePayeeCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AutomaticInvestmentsCollectionResult getAutomaticInvestmentCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addAutomaticInvestmentPlan(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AutomaticInvestmentRequest automaticInvestment, com.ws.gemini.wsdl.account.AchPayeeRequest achPayeeInfo) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status modifyAutomaticInvestmentPlan(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AutomaticInvestmentRequest automaticInvestment, com.ws.gemini.wsdl.account.AchPayeeRequest achPayeeInfo) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status deleteAutomaticInvestmentPlan(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, int automaticInvestmentID) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addAccountForCommonMailing(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountLinkagesRequest accountLinkages) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.StatementbyFormCategoryResult getStatementByFormCategory(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.StatementbyFormCategoryRequest statementbyFormCategory) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.StatementbyFormCategoryResult updateStatementByFormCategory(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.StatementbyFormCategoryRequest statementbyFormCategory) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.MailingAddressesResult getMailingAddressForMailingAddressType(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, org.apache.axis.types.UnsignedByte mailingAddressType) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateMailingAddresses(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber, com.ws.gemini.wsdl.account.MailingAddressesRequest mailingAddresses) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateSuccessorBeneficiaries(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.SuccessorBeneficiaryRequest successorBeneficiary) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addSuccessorBeneficiaries(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.SuccessorBeneficiaryRequest successorBeneficiary) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateBeneficiary529(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.Beneficiary529Request beneficiary529) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addAccountMessages(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountMessageRequest accountMessage) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status addAccountCustomField(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountCustomFieldRequest accountCustomField) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AssetAllocationModelWeightsResult getAssetAllocationModelWeights(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateAssetAllocationModel(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AssetAllocationModelsRequest assetAllocationModel) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.NewAccountResult createNewAccount(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountRequest account) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AccountCustomFieldValuesResult getAccountForCustomFieldValue(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountCustomFieldValuesRequest accountCustomFieldValueRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.PendingOrderCollectionResult getPendingTradesForAccount(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateDeliveryModeForEdocs(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.EdocsDeliveryModeRequest edocDeliveryModeRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.EdocsCollectionResult getEdocs(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.PrepaidActivityCollectionResult getPrepaidActivityCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.PrepaidActivityRequest prepaidActivityRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.PrepaidSummaryResult getPrepaidSummaryCollection(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.PrepaidSummaryRequest prepaidSummaryRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.FavoriteInstitutionsCollectionResult getFavoriteInstitutionsForBeneficiary(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateFavouriteInstitutionsForBeneficiary(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.UpdateFavoriteInstitutionsRequest updateFavoriteInstitutionsRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.AccountCustomFieldsCollectionResult getAccountCustomFields(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountNumber) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateAccountCustomFields(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.UpdateCustomFieldsRequest updateCustomFieldsRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.CustomFieldListValuesCollectionResult getCustomFieldListValues(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, java.lang.String accountCustomFieldDefinition) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.CDSCCalculatorResult calculateCDSCForAccount(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.CDSCCalculatorRequest cdscCalculatorRequest) throws java.rmi.RemoteException;
    public com.ws.gemini.wsdl.account.Status updateAccountDividendSetup(com.ws.gemini.wsdl.account.AuthenticateLogin userLogin, com.ws.gemini.wsdl.account.AccountDividendSetupRequest accountDividendSetupRequest) throws java.rmi.RemoteException;
}
