INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', 'KayHian.Without.Sing', 'A', 'Global portfolio without Singapore exposure', '4', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', '');
INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', 'KayHian.With.Sing', 'A', 'Global portfolio with Singapore exposure', '3', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', '');


INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.With.Sing', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.05', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.With.Sing', 'A', 'Commodity', 'Commodities', 'IAU.N', '30', '0', '0.05', '#5E5E5E', '0.0225', '0.75', '0.01', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.With.Sing', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0', '0.9', '#333F50', '0.0617', '0.75', '0.9', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.With.Sing', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0.1', '1', '#47566D', '0.0134', '0.75', '0.8', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.Without.Sing', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.05', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.Without.Sing', 'A', 'Commodity', 'Commodities', 'IAU.N', '30', '0', '0.05', '#5E5E5E', '0.0225', '0.75', '0.01', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.Without.Sing', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '0', '0', '0.9', '#333F50', '0.0617', '0.75', '0.9', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`) VALUES ('KayHian.Without.Sing', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0.1', '1', '#47566D', '0.0134', '0.75', '0.8', '2017-07-30 13:49:12');


INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Cash', 'Cash', 'Cash', 'A', '99999', '0', '1', '0.001', '0', '0', '2017-07-30 13:49:13');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Commodity', 'Precious Metals', 'IAU.N', 'A', '900', '0', '1', '0.0225', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', '0.25', '0.50', '0.069', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Equity', 'Singapore Equities', 'EWS.N', 'A', '100', '0.05', '0.10', '0.0722', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', '0.5', '0.75', '0.0617', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'Corporate Bonds ', 'LQDE.L', 'A', '610', '0.00', '0.60', '0.0206', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', '0.10', '0.20', '0.0264', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'Emerging Market Bonds', 'IEMB.L', 'A', '420', '0.05', '0.50', '0.0334', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'Emerging Market Local Bonds', 'IEML.L', 'A', '420', '0.20', '0.50', '0.011', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'Singapore Bonds', 'F00000MQNO.MSTA', 'A', '420', '0.25', '0.50', '0.0145', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', '0.05', '0.60', '0.0134', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.With.Sing', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', '0.00', '0.50', '0.0334', '0', '0', '2017-07-30 13:49:12');






INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Cash', 'Cash', 'Cash', 'A', '99999', '0', '1', '0.001', '0', '0', '2017-07-30 13:49:13');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Commodity', 'Precious Metals', 'IAU.N', 'A', '900', '0', '1', '0.0225', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', '0.25', '0.50', '0.069', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', '0.5', '0.75', '0.0617', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'Corporate Bonds ', 'LQDE.L', 'A', '610', '0.00', '0.60', '0.0206', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', '0.10', '0.20', '0.0264', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'Emerging Market Bonds', 'IEMB.L', 'A', '420', '0.05', '0.50', '0.0334', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'Emerging Market Local Bonds', 'IEML.L', 'A', '420', '0.20', '0.50', '0.011', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', '0.05', '0.60', '0.0134', '0', '0', '2017-07-30 13:49:12');
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`) VALUES ('KayHian.Without.Sing', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', '0.00', '0.50', '0.0334', '0', '0', '2017-07-30 13:49:12');






INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'Cash', 'Cash', '1', '2018-01-19', 'SGD', 'Cash', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'EWJ.N', 'EWJ.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'EWS.N', 'EWS.N', '1', '2017-07-30', 'SGD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'F00000MQNO.MSTA', 'F00000MQNO.MSTA', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IAU.N', 'IAU.N', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IEMB.L', 'IEMB.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IEML.L', 'IEML.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'IVV.N', 'IVV.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'LQDE.L', 'LQDE.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'SPY.N', 'SPY.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'VUSD.L', '1306.T', '0.09', '2017-07-30', 'JPY', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'VUSD.L', 'VAS.AX', '0.03', '2017-07-30', 'AUD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'VUSD.L', 'VEUR.L', '0.25', '2017-07-30', 'GBP', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'VUSD.L', 'VUSD.L', '0.6', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.Without.Sing', 'VUSD.L', 'XIC.TO', '0.03', '2017-07-30', 'CAD', 'Equity', 'SGD');




INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'Cash', 'Cash', '1', '2018-01-19', 'SGD', 'Cash', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'EWJ.N', 'EWJ.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'EWS.N', 'EWS.N', '1', '2017-07-30', 'SGD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'F00000MQNO.MSTA', 'F00000MQNO.MSTA', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IAU.N', 'IAU.N', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IEMB.L', 'IEMB.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IEML.L', 'IEML.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'IVV.N', 'IVV.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'SGD', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'LQDE.L', 'LQDE.L', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'SPY.N', 'SPY.N', '1', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'VUSD.L', '1306.T', '0.09', '2017-07-30', 'JPY', 'Fixed Income', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'VUSD.L', 'VAS.AX', '0.03', '2017-07-30', 'AUD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'VUSD.L', 'VEUR.L', '0.25', '2017-07-30', 'GBP', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'VUSD.L', 'VUSD.L', '0.6', '2017-07-30', 'USD', 'Equity', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `base_currency`, `style`, `dest_currency`) VALUES ('KayHian.With.Sing', 'VUSD.L', 'XIC.TO', '0.03', '2017-07-30', 'CAD', 'Equity', 'SGD');







INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', '1306.T', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', '99999', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', '120', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IAU.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', '900', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IEMB.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Emerging Market Bonds', 'Emerging Market Bonds', '420', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IEML.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Emerging Market Local Bonds', 'Emerging Market Local Bonds', '420', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', '500', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', '610', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', '600', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'LQDE.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Corporate Bonds ', 'Corporate Bonds ', '610', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'VAS.AX', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'VEUR.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.Without.Sing', 'XIC.TO', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');






INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', '1306.T', 'Equity', 'Equity Securities', '#333F50', '0', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', '99999', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '0', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', '120', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'EWS.N', 'Equity', 'Equity Securities', '#333F50', '0', 'Singapore Equities', 'Singapore Equities', '100', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'F00000MQNO.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', '420', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IAU.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', '900', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IEMB.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Emerging Market Bonds', 'Emerging Market Bonds', '420', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IEML.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Emerging Market Local Bonds', 'Emerging Market Local Bonds', '420', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', '500', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', '610', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', '600', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'LQDE.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Corporate Bonds ', 'Corporate Bonds ', '610', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'VAS.AX', 'Equity', 'Equity Securities', '#333F50', '0', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'VEUR.L', 'Equity', 'Equity Securities', '#333F50', '0', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '0', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasssortorder`, `type`, `created`) VALUES ('KayHian.With.Sing', 'XIC.TO', 'Equity', 'Equity Securities', '#333F50', '0', 'U.S. Equities', 'U.S. Equities', '150', 'OT', '2018-01-19 21:16:15');
