DELETE FROM `invdb`.`user_basket_access`
where theme like '%CITI'
or theme like '%SG%';

INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `baseCurrency`, `created`, `lastupdated`)
VALUES 
('CITI', '0.CITI', 'A', 'Grow Wealth', '1', 'Y', 'N', 'O', 'SGD', now(), null),
('CITI', 'T.0.CITI', 'A', 'Grow Wealth', '0', 'Y', 'N', 'O', 'SGD', now(), null),
('UOB', '0.SGWealthSGD', 'A', 'Grow Wealth', '1', 'Y', 'N', 'O', 'SGD', now(), null),
('UOB', 'T.0.SGWealthSGD', 'A', 'Grow Wealth', '0', 'Y', 'N', 'O', 'SGD', now(), null)
;

DELETE FROM `invdb`.`sec_assetclass_group`  
where theme like '%CITI'
or theme like '%SG%';

INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.CITI', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.0025', '#002D72', '0', '0.75', '0.01', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.CITI', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '0.05', '#007377', '0.06', '0.75', '0.01', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.CITI', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '0.9', '#0076C0', '0.09', '0.75', '0.9', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.CITI', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#00B0B9', '0.0424', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.SGWealthSGD', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.01', '#8E8E8E', '0', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.SGWealthSGD', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '0.05', '#5E5E5E', '0.06', '0.75', '0.01', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.SGWealthSGD', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '0.9', '#333F50', '0.09', '0.75', '0.9', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('0.SGWealthSGD', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#47566D', '0.0424', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.CITI', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.01', '#002D72', '0', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.CITI', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '0.05', '#007377', '0.06', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.CITI', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '0.9', '#0076C0', '0.09', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.CITI', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#00B0B9', '0.0424', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.SGWealth', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.01', '#8E8E8E', '0', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.SGWealthSGD', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '0.05', '#5E5E5E', '0.06', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.SGWealthSGD', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '0.9', '#333F50', '0.09', '0.75', '0.8', now(), null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.0.SGWealthSGD', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#47566D', '0.0424', '0.75', '0.8', now(), null);

DELETE FROM `invdb`.`sec_prime_asset_group`  
where theme like '%CITI'
or theme like '%SG%';

INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.0505', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Equity', 'C.N', 'A', '160', null, '0.01', '0.1', '0.087', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Large Cap', 'DAL.N', 'A', '163', null, '0', '0.04', '0.085', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.0909', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0', '0.07', '0.0758', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Equity', 'IBM.N', 'A', '170', null, '0.02', '0.04', '0.12', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.0808', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'A', '110', null, '0.03', '0.07', '0.0758', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Large Cap', 'MRK.N', 'A', '161', null, '0', '0.04', '0.095', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Japan Equities', 'SJPA.L', 'A', '130', null, '0.05', '0.07', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Large Cap', 'TOL.N', 'A', '164', null, '0', '0.04', '0.09', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'Large Cap', 'UL.N', 'A', '162', null, '0', '0.04', '0.08', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.1', '0.33', '0.0808', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Fixed Income', 'Pan Asia Bonds', '2821.HK', 'A', '400', null, '0.22', '0.23', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.08', '0.1', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.13', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', null, '0.14', '0.16', '0.0323', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.CITI', 'Fixed Income', 'Singapore Bonds', 'KV4.SI', 'A', '420', null, '0.22', '0.4', '0.0323', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.04', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.08', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0.04', '0.07', '0.065', null, null, now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.07', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'N', '110', null, '0.03', '0.07', '0.065', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'Japan Equities', 'SJPA.L', 'N', '130', null, '0.05', '0.07', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.32', '1', '0.07', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Fixed Income', 'Pan Asia Bonds', '2821.HK', 'A', '400', null, '0.25', '0.3', '0.03', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.14', '0.16', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.13', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'N', '600', null, '0.14', '0.16', '0.022', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('0.SGWealthSGD', 'Fixed Income', 'Singapore Bonds', 'KV4.SI', 'A', '420', null, '0.25', '0.6', '0.022', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.0505', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Equity', 'C.N', 'A', '160', null, '0.05', '0.1', '0.07', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Large Cap', 'DAL.N', 'A', '163', null, '0', '0.04', '0.085', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.0909', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0.04', '0.07', '0.0758', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Equity', 'IBM.N', 'A', '170', null, '0.05', '0.1', '0.12', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.0808', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'A', '110', null, '0.03', '0.07', '0.0758', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Large Cap', 'MRK.N', 'A', '161', null, '0', '0.04', '0.095', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Japan Equities', 'SJPA.L', 'A', '130', null, '0.05', '0.07', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Large Cap', 'TOL.N', 'A', '164', null, '0', '0.04', '0.09', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'Large Cap', 'UL.N', 'A', '162', null, '0', '0.04', '0.08', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.32', '0.33', '0.0808', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Fixed Income', 'Pan Asia Bonds', '2821.HK', 'A', '400', null, '0.22', '0.23', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.08', '0.1', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.13', '0.0606', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', null, '0.14', '0.16', '0.0323', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.CITI', 'Fixed Income', 'Singapore Bonds', 'KV4.SI', 'A', '420', null, '0.22', '0.4', '0.0323', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.06', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.1', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0.04', '0.07', '0.085', null, null, now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.07', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'A', '110', null, '0.03', '0.07', '0.085', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'Japan Equities', 'SJPA.L', 'A', '130', null, '0.05', '0.07', '0.07', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.32', '0.33', '0.08', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Fixed Income', 'Pan Asia Bonds', '2821.HK', 'A', '400', null, '0.25', '0.3', '0.05', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.14', '0.16', '0.06', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.13', '0.06', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', null, '0.14', '0.16', '0.03', '0', '0', now(), null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.0.SGWealthSGD', 'Fixed Income', 'Singapore Bonds', 'KV4.SI', 'A', '420', null, '0.25', '0.6', '0.0323', '0', '0', now(), null);

DELETE FROM `invdb`.`sec_rbsa`  
where theme like '%CITI'
or theme like '%SG%';

INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`)
SELECT `theme`, `ticker`, `ticker`, 1.0, curdate()
FROM `invdb`.`sec_prime_asset_group`
where theme like '%CITI'
or theme like '%SG%';
;

DELETE FROM `invdb`.`sec_asset_mapping`;

CALL `invdb`.`sp_upload_sec_asset_mapping`();


