CREATE TABLE IF NOT EXISTS service.`country_master` (
  `iso` char(2) NOT NULL,
  `name` varchar(80) NOT NULL,
  `nicename` varchar(80) NOT NULL,
  `iso3` char(3) DEFAULT NULL,
  `numcode` smallint(6) DEFAULT NULL,
  `phonecode` int(5) NOT NULL,
  `status` char(1) NOT NULL,
  PRIMARY KEY (`iso`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create view service.vw_country as select * from service.country_master;

INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AD', 'Andorra', 'Andorra', 'AND', '20', '376', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AE', 'United Arab Emirates', 'United Arab Emirates', 'ARE', '784', '971', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AF', 'Afghanistan', 'Afghanistan', 'AFG', '4', '93', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', '28', '1268', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AI', 'Anguilla', 'Anguilla', 'AIA', '660', '1264', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AL', 'Albania', 'Albania', 'ALB', '8', '355', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AM', 'Armenia', 'Armenia', 'ARM', '51', '374', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AN', 'Netherlands Antilles', 'Netherlands Antilles', 'ANT', '530', '599', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AO', 'Angola', 'Angola', 'AGO', '24', '244', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AP', 'Asia / Pacific Region', 'Asia / Pacific Region', '0', '0', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('AQ', 'Antarctica', 'Antarctica', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AR', 'Argentina', 'Argentina', 'ARG', '32', '54', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AS', 'American Samoa', 'American Samoa', 'ASM', '16', '1684', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AT', 'Austria', 'Austria', 'AUT', '40', '43', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AU', 'Australia', 'Australia', 'AUS', '36', '61', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AW', 'Aruba', 'Aruba', 'ABW', '533', '297', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AX', 'Aland Islands', 'Aland Islands', 'ALA', '248', '358', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('AZ', 'Azerbaijan', 'Azerbaijan', 'AZE', '31', '994', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', '70', '387', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BB', 'Barbados', 'Barbados', 'BRB', '52', '1246', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BD', 'Bangladesh', 'Bangladesh', 'BGD', '50', '880', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BE', 'Belgium', 'Belgium', 'BEL', '56', '32', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BF', 'Burkina Faso', 'Burkina Faso', 'BFA', '854', '226', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BG', 'Bulgaria', 'Bulgaria', 'BGR', '100', '359', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BH', 'Bahrain', 'Bahrain', 'BHR', '48', '973', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BI', 'Burundi', 'Burundi', 'BDI', '108', '257', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BJ', 'Benin', 'Benin', 'BEN', '204', '229', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BL', 'Saint Barthelemy', 'Saint Barthelemy', 'BLM', '652', '590', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BM', 'Bermuda', 'Bermuda', 'BMU', '60', '1441', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BN', 'Brunei Darussalam', 'Brunei Darussalam', 'BRN', '96', '673', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BO', 'Bolivia', 'Bolivia', 'BOL', '68', '591', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', '599', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BR', 'Brazil', 'Brazil', 'BRA', '76', '55', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BS', 'Bahamas', 'Bahamas', 'BHS', '44', '1242', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BT', 'Bhutan', 'Bhutan', 'BTN', '64', '975', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('BV', 'Bouvet Island', 'Bouvet Island', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BW', 'Botswana', 'Botswana', 'BWA', '72', '267', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BY', 'Belarus', 'Belarus', 'BLR', '112', '375', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('BZ', 'Belize', 'Belize', 'BLZ', '84', '501', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CA', 'Canada', 'Canada', 'CAN', '124', '1', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', '672', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CD', 'Congo, the Democratic Republic of the', 'Congo, the Democratic Republic of the', 'COD', '180', '243', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CF', 'Central African Republic', 'Central African Republic', 'CAF', '140', '236', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CG', 'Congo', 'Congo', 'COG', '178', '242', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CH', 'Switzerland', 'Switzerland', 'CHE', '756', '41', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CI', 'Cote D\'Ivoire', 'Cote D\'Ivoire', 'CIV', '384', '225', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CK', 'Cook Islands', 'Cook Islands', 'COK', '184', '682', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CL', 'Chile', 'Chile', 'CHL', '152', '56', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CM', 'Cameroon', 'Cameroon', 'CMR', '120', '237', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CN', 'China', 'China', 'CHN', '156', '86', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CO', 'Colombia', 'Colombia', 'COL', '170', '57', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CR', 'Costa Rica', 'Costa Rica', 'CRI', '188', '506', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('CS', 'Serbia and Montenegro', 'Serbia and Montenegro', '381', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CU', 'Cuba', 'Cuba', 'CUB', '192', '53', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CV', 'Cape Verde', 'Cape Verde', 'CPV', '132', '238', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CW', 'Curacao', 'Curacao', 'CUW', '531', '599', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('CX', 'Christmas Island', 'Christmas Island', '61', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CY', 'Cyprus', 'Cyprus', 'CYP', '196', '357', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('CZ', 'Czech Republic', 'Czech Republic', 'CZE', '203', '420', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DE', 'Germany', 'Germany', 'DEU', '276', '49', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DJ', 'Djibouti', 'Djibouti', 'DJI', '262', '253', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DK', 'Denmark', 'Denmark', 'DNK', '208', '45', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DM', 'Dominica', 'Dominica', 'DMA', '212', '1767', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DO', 'Dominican Republic', 'Dominican Republic', 'DOM', '214', '1809', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('DZ', 'Algeria', 'Algeria', 'DZA', '12', '213', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('EC', 'Ecuador', 'Ecuador', 'ECU', '218', '593', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('EE', 'Estonia', 'Estonia', 'EST', '233', '372', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('EG', 'Egypt', 'Egypt', 'EGY', '818', '20', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('EH', 'Western Sahara', 'Western Sahara', 'ESH', '732', '212', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ER', 'Eritrea', 'Eritrea', 'ERI', '232', '291', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ES', 'Spain', 'Spain', 'ESP', '724', '34', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ET', 'Ethiopia', 'Ethiopia', 'ETH', '231', '251', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FI', 'Finland', 'Finland', 'FIN', '246', '358', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FJ', 'Fiji', 'Fiji', 'FJI', '242', '679', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FK', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'FLK', '238', '500', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FM', 'Micronesia, Federated States of', 'Micronesia, Federated States of', 'FSM', '583', '691', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FO', 'Faroe Islands', 'Faroe Islands', 'FRO', '234', '298', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('FR', 'France', 'France', 'FRA', '250', '33', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GA', 'Gabon', 'Gabon', 'GAB', '266', '241', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GB', 'United Kingdom', 'United Kingdom', 'GBR', '826', '44', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GD', 'Grenada', 'Grenada', 'GRD', '308', '1473', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GE', 'Georgia', 'Georgia', 'GEO', '268', '995', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GF', 'French Guiana', 'French Guiana', 'GUF', '254', '594', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GG', 'Guernsey', 'Guernsey', 'GGY', '831', '44', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GH', 'Ghana', 'Ghana', 'GHA', '288', '233', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GI', 'Gibraltar', 'Gibraltar', 'GIB', '292', '350', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GL', 'Greenland', 'Greenland', 'GRL', '304', '299', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GM', 'Gambia', 'Gambia', 'GMB', '270', '220', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GN', 'Guinea', 'Guinea', 'GIN', '324', '224', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GP', 'Guadeloupe', 'Guadeloupe', 'GLP', '312', '590', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GQ', 'Equatorial Guinea', 'Equatorial Guinea', 'GNQ', '226', '240', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GR', 'Greece', 'Greece', 'GRC', '300', '30', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GT', 'Guatemala', 'Guatemala', 'GTM', '320', '502', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GU', 'Guam', 'Guam', 'GUM', '316', '1671', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'GNB', '624', '245', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('GY', 'Guyana', 'Guyana', 'GUY', '328', '592', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('HK', 'Hong Kong', 'Hong Kong', 'HKG', '344', '852', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('HM', 'Heard Island and Mcdonald Islands', 'Heard Island and Mcdonald Islands', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('HN', 'Honduras', 'Honduras', 'HND', '340', '504', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('HR', 'Croatia', 'Croatia', 'HRV', '191', '385', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('HT', 'Haiti', 'Haiti', 'HTI', '332', '509', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('HU', 'Hungary', 'Hungary', 'HUN', '348', '36', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ID', 'Indonesia', 'Indonesia', 'IDN', '360', '62', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IE', 'Ireland', 'Ireland', 'IRL', '372', '353', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IL', 'Israel', 'Israel', 'ISR', '376', '972', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IM', 'Isle of Man', 'Isle of Man', 'IMN', '833', '44', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IN', 'India', 'India', 'IND', '356', '91', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', '246', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IQ', 'Iraq', 'Iraq', 'IRQ', '368', '964', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IR', 'Iran, Islamic Republic of', 'Iran, Islamic Republic of', 'IRN', '364', '98', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IS', 'Iceland', 'Iceland', 'ISL', '352', '354', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('IT', 'Italy', 'Italy', 'ITA', '380', '39', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('JE', 'Jersey', 'Jersey', 'JEY', '832', '44', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('JM', 'Jamaica', 'Jamaica', 'JAM', '388', '1876', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('JO', 'Jordan', 'Jordan', 'JOR', '400', '962', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('JP', 'Japan', 'Japan', 'JPN', '392', '81', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KE', 'Kenya', 'Kenya', 'KEN', '404', '254', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KG', 'Kyrgyzstan', 'Kyrgyzstan', 'KGZ', '417', '996', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KH', 'Cambodia', 'Cambodia', 'KHM', '116', '855', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KI', 'Kiribati', 'Kiribati', 'KIR', '296', '686', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KM', 'Comoros', 'Comoros', 'COM', '174', '269', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KNA', '659', '1869', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KP', 'Korea, Democratic People\'s Republic of', 'Korea, Democratic People\'s Republic of', 'PRK', '408', '850', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KR', 'Korea, Republic of', 'Korea, Republic of', 'KOR', '410', '82', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KW', 'Kuwait', 'Kuwait', 'KWT', '414', '965', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KY', 'Cayman Islands', 'Cayman Islands', 'CYM', '136', '1345', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('KZ', 'Kazakhstan', 'Kazakhstan', 'KAZ', '398', '7', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LA', 'Lao People\'s Democratic Republic', 'Lao People\'s Democratic Republic', 'LAO', '418', '856', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LB', 'Lebanon', 'Lebanon', 'LBN', '422', '961', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LC', 'Saint Lucia', 'Saint Lucia', 'LCA', '662', '1758', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LI', 'Liechtenstein', 'Liechtenstein', 'LIE', '438', '423', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LK', 'Sri Lanka', 'Sri Lanka', 'LKA', '144', '94', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LR', 'Liberia', 'Liberia', 'LBR', '430', '231', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LS', 'Lesotho', 'Lesotho', 'LSO', '426', '266', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LT', 'Lithuania', 'Lithuania', 'LTU', '440', '370', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LU', 'Luxembourg', 'Luxembourg', 'LUX', '442', '352', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LV', 'Latvia', 'Latvia', 'LVA', '428', '371', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('LY', 'Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya', 'LBY', '434', '218', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MA', 'Morocco', 'Morocco', 'MAR', '504', '212', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MC', 'Monaco', 'Monaco', 'MCO', '492', '377', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MD', 'Moldova, Republic of', 'Moldova, Republic of', 'MDA', '498', '373', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ME', 'Montenegro', 'Montenegro', 'MNE', '499', '382', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MF', 'Saint Martin', 'Saint Martin', 'MAF', '663', '590', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MG', 'Madagascar', 'Madagascar', 'MDG', '450', '261', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MH', 'Marshall Islands', 'Marshall Islands', 'MHL', '584', '692', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of', 'Macedonia, the Former Yugoslav Republic of', 'MKD', '807', '389', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ML', 'Mali', 'Mali', 'MLI', '466', '223', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MM', 'Myanmar', 'Myanmar', 'MMR', '104', '95', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MN', 'Mongolia', 'Mongolia', 'MNG', '496', '976', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MO', 'Macao', 'Macao', 'MAC', '446', '853', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'MNP', '580', '1670', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MQ', 'Martinique', 'Martinique', 'MTQ', '474', '596', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MR', 'Mauritania', 'Mauritania', 'MRT', '478', '222', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MS', 'Montserrat', 'Montserrat', 'MSR', '500', '1664', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MT', 'Malta', 'Malta', 'MLT', '470', '356', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MU', 'Mauritius', 'Mauritius', 'MUS', '480', '230', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MV', 'Maldives', 'Maldives', 'MDV', '462', '960', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MW', 'Malawi', 'Malawi', 'MWI', '454', '265', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MX', 'Mexico', 'Mexico', 'MEX', '484', '52', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MY', 'Malaysia', 'Malaysia', 'MYS', '458', '60', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('MZ', 'Mozambique', 'Mozambique', 'MOZ', '508', '258', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NA', 'Namibia', 'Namibia', 'NAM', '516', '264', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NC', 'New Caledonia', 'New Caledonia', 'NCL', '540', '687', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NE', 'Niger', 'Niger', 'NER', '562', '227', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NF', 'Norfolk Island', 'Norfolk Island', 'NFK', '574', '672', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NG', 'Nigeria', 'Nigeria', 'NGA', '566', '234', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NI', 'Nicaragua', 'Nicaragua', 'NIC', '558', '505', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NL', 'Netherlands', 'Netherlands', 'NLD', '528', '31', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NO', 'Norway', 'Norway', 'NOR', '578', '47', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NP', 'Nepal', 'Nepal', 'NPL', '524', '977', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NR', 'Nauru', 'Nauru', 'NRU', '520', '674', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NU', 'Niue', 'Niue', 'NIU', '570', '683', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('NZ', 'New Zealand', 'New Zealand', 'NZL', '554', '64', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('OM', 'Oman', 'Oman', 'OMN', '512', '968', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PA', 'Panama', 'Panama', 'PAN', '591', '507', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PE', 'Peru', 'Peru', 'PER', '604', '51', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PF', 'French Polynesia', 'French Polynesia', 'PYF', '258', '689', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PG', 'Papua New Guinea', 'Papua New Guinea', 'PNG', '598', '675', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PH', 'Philippines', 'Philippines', 'PHL', '608', '63', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PK', 'Pakistan', 'Pakistan', 'PAK', '586', '92', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PL', 'Poland', 'Poland', 'POL', '616', '48', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'SPM', '666', '508', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PN', 'Pitcairn', 'Pitcairn', 'PCN', '612', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PR', 'Puerto Rico', 'Puerto Rico', 'PRI', '630', '1787', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('PS', 'Palestinian Territory, Occupied', 'Palestinian Territory, Occupied', '970', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PT', 'Portugal', 'Portugal', 'PRT', '620', '351', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PW', 'Palau', 'Palau', 'PLW', '585', '680', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('PY', 'Paraguay', 'Paraguay', 'PRY', '600', '595', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('QA', 'Qatar', 'Qatar', 'QAT', '634', '974', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('RE', 'Reunion', 'Reunion', 'REU', '638', '262', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('RO', 'Romania', 'Romania', 'ROM', '642', '40', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('RS', 'Serbia', 'Serbia', 'SRB', '688', '381', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('RU', 'Russian Federation', 'Russian Federation', 'RUS', '643', '7', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('RW', 'Rwanda', 'Rwanda', 'RWA', '646', '250', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SA', 'Saudi Arabia', 'Saudi Arabia', 'SAU', '682', '966', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SB', 'Solomon Islands', 'Solomon Islands', 'SLB', '90', '677', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SC', 'Seychelles', 'Seychelles', 'SYC', '690', '248', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SD', 'Sudan', 'Sudan', 'SDN', '736', '249', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SE', 'Sweden', 'Sweden', 'SWE', '752', '46', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SG', 'Singapore', 'Singapore', 'SGP', '702', '65', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SH', 'Saint Helena', 'Saint Helena', 'SHN', '654', '290', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SI', 'Slovenia', 'Slovenia', 'SVN', '705', '386', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'SJM', '744', '47', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SK', 'Slovakia', 'Slovakia', 'SVK', '703', '421', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SL', 'Sierra Leone', 'Sierra Leone', 'SLE', '694', '232', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SM', 'San Marino', 'San Marino', 'SMR', '674', '378', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SN', 'Senegal', 'Senegal', 'SEN', '686', '221', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SO', 'Somalia', 'Somalia', 'SOM', '706', '252', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SR', 'Suriname', 'Suriname', 'SUR', '740', '597', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SS', 'South Sudan', 'South Sudan', 'SSD', '728', '211', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ST', 'Sao Tome and Principe', 'Sao Tome and Principe', 'STP', '678', '239', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SV', 'El Salvador', 'El Salvador', 'SLV', '222', '503', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SX', 'Sint Maarten', 'Sint Maarten', 'SXM', '534', '1', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SY', 'Syrian Arab Republic', 'Syrian Arab Republic', 'SYR', '760', '963', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('SZ', 'Swaziland', 'Swaziland', 'SWZ', '748', '268', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TCA', '796', '1649', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TD', 'Chad', 'Chad', 'TCD', '148', '235', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('TF', 'French Southern Territories', 'French Southern Territories', '0', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TG', 'Togo', 'Togo', 'TGO', '768', '228', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TH', 'Thailand', 'Thailand', 'THA', '764', '66', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TJ', 'Tajikistan', 'Tajikistan', 'TJK', '762', '992', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TK', 'Tokelau', 'Tokelau', 'TKL', '772', '690', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('TL', 'Timor-Leste', 'Timor-Leste', '670', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TM', 'Turkmenistan', 'Turkmenistan', 'TKM', '795', '7370', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TN', 'Tunisia', 'Tunisia', 'TUN', '788', '216', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TO', 'Tonga', 'Tonga', 'TON', '776', '676', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TR', 'Turkey', 'Turkey', 'TUR', '792', '90', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TT', 'Trinidad and Tobago', 'Trinidad and Tobago', 'TTO', '780', '1868', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TV', 'Tuvalu', 'Tuvalu', 'TUV', '798', '688', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TW', 'Taiwan, Province of China', 'Taiwan, Province of China', 'TWN', '158', '886', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('TZ', 'Tanzania, United Republic of', 'Tanzania, United Republic of', 'TZA', '834', '255', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('UA', 'Ukraine', 'Ukraine', 'UKR', '804', '380', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('UG', 'Uganda', 'Uganda', 'UGA', '800', '256', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', '1', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('US', 'United States', 'United States', 'USA', '840', '1', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('UY', 'Uruguay', 'Uruguay', 'URY', '858', '598', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('UZ', 'Uzbekistan', 'Uzbekistan', 'UZB', '860', '998', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VA', 'Holy See (Vatican City State)', 'Holy See (Vatican City State)', 'VAT', '336', '39', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT', '670', '1784', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VE', 'Venezuela', 'Venezuela', 'VEN', '862', '58', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VG', 'Virgin Islands, British', 'Virgin Islands, British', 'VGB', '92', '1284', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VI', 'Virgin Islands, U.s.', 'Virgin Islands, U.s.', 'VIR', '850', '1340', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VN', 'Viet Nam', 'Viet Nam', 'VNM', '704', '84', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('VU', 'Vanuatu', 'Vanuatu', 'VUT', '548', '678', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('WF', 'Wallis and Futuna', 'Wallis and Futuna', 'WLF', '876', '681', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('WS', 'Samoa', 'Samoa', 'WSM', '882', '684', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('XK', 'Kosovo', 'Kosovo', '---', '0', '381', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('YE', 'Yemen', 'Yemen', 'YEM', '887', '967', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `phonecode`, `status`) VALUES ('YT', 'Mayotte', 'Mayotte', '269', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ZA', 'South Africa', 'South Africa', 'ZAF', '710', '27', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ZM', 'Zambia', 'Zambia', 'ZMB', '894', '260', 'A');
INSERT INTO `service`.`country_master` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('ZW', 'Zimbabwe', 'Zimbabwe', 'ZWE', '716', '263', 'A');
