DELETE FROM `invdb`.`web_site_info` where url = 'invessence';
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'ARCHIVE.CLOSED', 'A', '10', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'ARCHIVE.INACTIVE', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'ARCHIVE.UNOPENED', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'CSS.CUSTODY', 'A', 'css/inv.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'CSS.CUSTOM', 'A', 'css/inv.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'CSS.DIR', 'A', 'inv', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'CUSTODY.SERVICE', 'A', 'URL', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'CUSTODY.URL', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DEFAULT.MODEL', 'A', '0.Wealth', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DEFAULT.ADVISOR', 'A', 'Invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DEFAULT.REP', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DIR.CONSUMER', 'A', 'inv', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DIR.CUSTODY', 'A', null, 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'DIR.TEMPLATE', 'A', '/template/common/spark', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'EMAIL.MAIN', 'A', 'info@invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'EMAIL.OPERATION', 'A', 'operations@invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'EMAIL.SUPPORT', 'A', 'support@invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'EMAIL.USER', 'A', 'noreply@invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'HTML.FORGOT', 'A', 'invessence-Forgot.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'HTML.LOCKED', 'A', 'invessence-Locked.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'HTML.RESET', 'A', 'invessence-Reset.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'HTML.WELCOME', 'A', 'invessence-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'HTML.WELCOME.ADV', 'A', 'invessence-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'INVESTMENT.MIN1ST', 'A', '2000', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'INVESTMENT.MIN2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'INVESTMENT.RECURRING1ST', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'INVESTMENT.RECURRING2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'PHONE.MAIN', 'A', '(201) 977-1954', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'PHONE.SUPPORT', 'A', '(201) 977-1955', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'SUBJECT.EMAIL.ACTIVATE', 'A', 'Welcome to Invessence – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'SUBJECT.EMAIL.LOCKED', 'A', 'Invessence – Account is locked', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'SUBJECT.EMAIL.RESET', 'A', 'Invessence – Reset Your Password', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'SUBJECT.EMAIL.WELCOME', 'A', 'Welcome to Invessence – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'URL.SECURE', 'A', 'https://invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'URL.WEBSITE', 'A', 'http://invessence.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.COMPANYNAME', 'A', 'Invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.COPYRIGHT', 'A', 'Invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.GOOGLEANALYTICS', 'A', 'inv_googleanalytics.js', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.LOGO', 'A', 'images/logo/LOGO.png', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.LOGOLIB', 'A', 'invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.LOGOSIZE', 'A', '200px', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.MODE', 'A', 'PROD', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.THEME', 'A', 'spark', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.THEMELIB', 'A', 'spark-layout', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('invessence', 'WEB.SSLSEAL', 'A', null, 'N', now(), NULL);
