DELETE FROM `invdb`.`web_site_info` where url = 'uob';
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.CLOSED', 'A', '10', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.INACTIVE', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.UNOPENED', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.CUSTODY', 'A', 'css/uob.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.CUSTOM', 'A', 'css/uob.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.DIR', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CUSTODY.SERVICE', 'A', 'URL', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CUSTODY.URL', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DEFAULT.MODEL', 'A', '0.SGWealth', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DEFAULT.ADVISOR', 'A', 'UOB', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DEFAULT.REP', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.CONSUMER', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.CUSTODY', 'A', null, 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.TEMPLATE', 'A', '/template/common/invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.MAIN', 'A', 'info@uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.OPERATION', 'A', 'operations@uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.SUPPORT', 'A', 'support@uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.USER', 'A', 'noreply@uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.FORGOT', 'A', 'UOBKH-Forgot.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.LOCKED', 'A', 'UOBKH-Locked.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.RESET', 'A', 'UOBKH-Reset.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.WELCOME', 'A', 'UOBKH-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.WELCOME.ADV', 'A', 'UOBKH-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.MIN1ST', 'A', '2000', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.MIN2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.RECURRING1ST', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.RECURRING2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'PHONE.MAIN', 'A', '(XXX) XXX-XXXX', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'PHONE.SUPPORT', 'A', '(XXX) XXX-XXXX', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.ACTIVATE', 'A', 'Welcome to UOB Kay Hian – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.LOCKED', 'A', 'UOB Kay Hian – Account is locked', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.RESET', 'A', 'UOB Kay Hian – Reset Your Password', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.WELCOME', 'A', 'Welcome to UOB Kay Hian – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'URL.SECURE', 'A', 'https://uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'URL.WEBSITE', 'A', 'http://uobkh.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.COMPANYNAME', 'A', 'UOB Kay Hian', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.COPYRIGHT', 'A', 'UOB Kay Hian', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.GOOGLEANALYTICS', 'A', 'inv_googleanalytics.js', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGO', 'A', 'images/logo/uobkh.png', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGOLIB', 'A', 'invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGOSIZE', 'A', '200px', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.MODE', 'A', 'PROD', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.THEME', 'A', 'invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.THEMELIB', 'A', 'invessence-layout', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'PRODUCT.NAME', 'A', 'UOBKH', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'MENU.AGGREGRATION', 'A', 'User', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CHART.ASSET.ALLOCATION', 'A', 'HIGHCHART.2DDONUT', 'N', '2017-02-21 20:02:19', null);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CHART.RECOMMENDED.ASSET.ALLOCATION', 'A', 'PRIMEFACES.BARCHART', 'N', '2017-02-21 20:02:19', null);
