DELETE FROM `invdb`.`web_site_info` where url = 'uob';
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.CLOSED', 'A', '10', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.INACTIVE', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'ARCHIVE.UNOPENED', 'A', '30', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.CUSTODY', 'A', 'css/uob.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.CUSTOM', 'A', 'css/uob.css', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CSS.DIR', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CUSTODY.SERVICE', 'A', 'URL', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'CUSTODY.URL', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DEFAULT.MODEL', 'A', 'UOB', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DEFAULT.REP', 'A', '', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.CONSUMER', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.CUSTODY', 'A', null, 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'DIR.TEMPLATE', 'A', '/template/common/spark', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.MAIN', 'A', 'info@uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.OPERATION', 'A', 'operations@uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.SUPPORT', 'A', 'support@uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'EMAIL.USER', 'A', 'noreply@uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.FORGOT', 'A', 'uob-Forgot.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.LOCKED', 'A', 'uob-Locked.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.RESET', 'A', 'uob-Reset.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.WELCOME', 'A', 'uob-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'HTML.WELCOME.ADV', 'A', 'uob-Welcome.htm', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.MIN1ST', 'A', '2000', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.MIN2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.RECURRING1ST', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'INVESTMENT.RECURRING2ND', 'A', '50', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'PHONE.MAIN', 'A', '(XXX) XXX-XXXX', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'PHONE.SUPPORT', 'A', '(XXX) XXX-XXXX', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.ACTIVATE', 'A', 'Welcome to uob – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.LOCKED', 'A', 'uob – Account is locked', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.RESET', 'A', 'uob – Reset Your Password', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'SUBJECT.EMAIL.WELCOME', 'A', 'Welcome to uob – Activate Your Account', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'URL.SECURE', 'A', 'https://uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'URL.WEBSITE', 'A', 'http://uob.com', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.COMPANYNAME', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.COPYRIGHT', 'A', 'uob', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.GOOGLEANALYTICS', 'A', 'inv_googleanalytics.js', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGO', 'A', 'images/logo/uobkh.png', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGOLIB', 'A', 'invessence', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.LOGOSIZE', 'A', '200px', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.MODE', 'A', 'PROD', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.THEME', 'A', 'spark', 'N', '2016-12-16 22:20:19', NULL);
INSERT INTO `invdb`.`web_site_info` (`url`, `name`, `status`, `value`, `encrFlag`, `created`, `updated`) VALUES ('uob', 'WEB.THEMELIB', 'A', 'spark-layout', 'N', '2016-12-16 22:20:19', NULL);
