truncate table invdb.sec_exchangerate_master;
truncate table invdb.sec_exchangerate_source;
truncate table invdb.sec_source_mapping;
delete from invdb.sec_asset_mapping where theme like '%UOB%';
delete from invdb.sec_assetclass_group where theme like '%UOB%';
delete from invdb.sec_prime_asset_group where theme like '%UOB%';
delete from invdb.sec_rbsa where theme like '%UOB%';
delete from invdb.user_basket_access where theme like '%UOB%';


INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('1306.T', '1306.T', 'FIS', 'Y', 'Y', 'JPY', 'SGD', 'JPYSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('2821.HK', '2821.HK', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('BIL.N', 'BIL.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('EIMI.L', 'EIMI.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('ES3.SI', 'ES3.SI', 'FIS', 'Y', 'N', 'SGD', 'SGD', '', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('EWJ.N', 'EWJ.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('EWS.N', 'EWS.N', 'FIS', 'Y', 'N', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('F00000MQNO.MSTA', 'F00000MQNO.MSTA', 'FIS', 'Y', 'N', 'SGD', 'SGD', '', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', 'FIS', 'Y', 'N', 'SGD', 'SGD', '', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('GLD.N', 'GLD.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IAU.N', 'IAU.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IBM.N', 'IBM.N', 'FIS', 'N', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IEMB.L', 'IEMB.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IEML.L', 'IEML.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IHYG.L', 'IHYG.L', 'FIS', 'Y', 'Y', 'EUR', 'SGD', 'EURSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IHYU.L', 'IHYU.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IMEU.L', 'IMEU.L', 'FIS', 'Y', 'Y', 'GBX', 'SGD', 'GBPSGD', '0.01', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IPXJ.L', 'IPXJ.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IUAG.L', 'IUAG.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('IVV.N', 'IVV.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('JNK.N', 'JNK.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('KV4.SI', 'KV4.SI', 'FIS', 'Y', 'N', 'SGD', 'SGD', '', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('LQDE.L', 'LQDE.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('SJPA.L', 'SJPA.L', 'FIS', 'Y', 'Y', 'GBX', 'SGD', 'GBPSGD', '0.01', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('SPY.N', 'SPY.N', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('VAS.AX', 'VAS.AX', 'FIS', 'Y', 'Y', 'AUD', 'SGD', 'AUDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('VEUR.L', 'VEUR.L', 'FIS', 'Y', 'Y', 'GBP', 'SGD', 'GBPSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('VUSD.L', 'VUSD.L', 'FIS', 'Y', 'Y', 'USD', 'SGD', 'USDSGD', '1', '0.5');
INSERT INTO `invdb`.`sec_source_mapping` (`sec_ticker`, `ticker_source_name`, `tickersource`, `pricing_required`, `exchange_required`, `base_currency`, `dest_currency`, `currency_exchange_cd`, `multiplying_factor`, `return_threshold`) VALUES ('XIC.TO', 'XIC.TO', 'FIS', 'Y', 'Y', 'CAD', 'SGD', 'CADSGD', '1', '0.5');

INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('EURSGD', 'A', 'FIS', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('GBPSGD', 'A', 'FIS', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('HKDUSD', 'A', 'FIS', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('SGDAUD', 'A', 'FIS', '2017-11-28', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('SGDCAD', 'A', 'FIS', '2017-11-28', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('SGDJPY', 'A', 'FIS', '2017-11-28', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('SGDUSD', 'A', 'FIS', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('USDEUR', 'A', 'FIS', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_source` (`symbol`, `status`, `source`, `created`, `updated`) VALUES ('USDGBP', 'A', 'FIS', '2017-06-03', null);

DROP TABLE IF EXISTS `invdb`.`sec_exchangerate_master`;

CREATE TABLE `sec_exchangerate_master` (
  `symbol` varchar(20) NOT NULL,
  `status` varchar(1) DEFAULT 'A' COMMENT 'A - Active,I - Inactive',
  `fromCurrency` varchar(20) NOT NULL,
  `toCurrency` varchar(20) NOT NULL,
  `description` varchar(100) NOT NULL,
  `created` date DEFAULT NULL,
  `updated` date DEFAULT NULL,
  PRIMARY KEY (`symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('AUDUSD', 'N', 'AUD', 'USD', 'AUD to USD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('CADUSD', 'N', 'CAD', 'USD', 'CAD to USD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('EURSGD', 'A', 'EUR', 'SGD', 'Euro to SGD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('GBPSGD', 'A', 'GBP', 'SGD', 'GBP to SGD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('HKDUSD', 'A', 'HKD', 'USD', 'HKD to USD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('JPYUSD', 'N', 'JPY', 'USD', 'JPY to USD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('SGDAUD', 'A', 'SGD', 'AUD', 'SGD to AUD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('SGDCAD', 'A', 'SGD', 'CAD', 'SGD to CAD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('SGDJPY', 'A', 'SGD', 'JPY', 'SGD to JPY', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('SGDUSD', 'A', 'SGD', 'USD', 'Singapore Dollar to USD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('USDAUD', 'N', 'USD', 'AUD', 'USD to AUD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('USDCAD', 'N', 'USD', 'CAD', 'USD to CAD', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('USDEUR', 'A', 'USD', 'EUR', 'USD to EURO', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('USDGBP', 'A', 'USD', 'GBP', 'USD to GBP', '2017-06-03', null);
INSERT INTO `invdb`.`sec_exchangerate_master` (`symbol`, `status`, `fromCurrency`, `toCurrency`, `description`, `created`, `updated`) VALUES ('USDJPY', 'N', 'USD', 'JPY', 'USD to JPY', '2017-06-03', null);

INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.05', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB', 'A', 'Commodity', 'Commodities', 'IAU.N', '30', '0', '0.05', '#5E5E5E', '0.0225', '0.75', '0.01', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0', '0.9', '#333F50', '0.0617', '0.75', '0.9', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0.1', '1', '#47566D', '0.0134', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB.Sing', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.05', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB.Sing', 'A', 'Commodity', 'Commodities', 'IAU.N', '30', '0', '0.05', '#5E5E5E', '0.0225', '0.75', '0.01', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB.Sing', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '0', '0', '0.9', '#333F50', '0.0617', '0.75', '0.9', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('8.UOB.Sing', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0.1', '1', '#47566D', '0.0134', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '0.01', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '0.05', '#5E5E5E', '0.06', '0.75', '0.01', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '0.9', '#333F50', '0.09', '0.75', '0.9', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#47566D', '0.0424', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB.Sing', 'A', 'Cash', 'Cash', 'BIL.N', '40', '0', '1', '#8E8E8E', '0', '0.75', '0.8', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB.Sing', 'A', 'Commodity', 'Commodities', 'GLD.N', '30', '0.02', '1', '#5E5E5E', '0.04', '0.75', '0.01', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB.Sing', 'A', 'Equity', 'Equity Securities', 'VUSD.L', '10', '0.1', '1', '#333F50', '0.07', '0.75', '0.9', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_assetclass_group` (`theme`, `status`, `assetclass`, `displayName`, `ticker`, `sortorder`, `lowerBound`, `upperBound`, `color`, `averageReturn`, `riskAdjustment`, `endAllocation`, `created`, `lastupdated`) VALUES ('T.8.UOB.Sing', 'A', 'Fixed Income', 'Fixed Income Securities', 'IUAG.L', '20', '0', '1', '#47566D', '0.022', '0.75', '0.8', '2017-07-30 13:49:12', null);


INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0.001', '0', '0', '2017-07-30 13:49:13', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Commodity', 'Precious Metals', 'IAU.N', 'A', '900', null, '0', '1', '0.0225', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.25', '0.5', '0.069', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.5', '0.75', '0.0617', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'Corporate Bonds ', 'LQDE.L', 'A', '610', null, '0.05', '1', '0.0206', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0', '0.2', '0.0264', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'Emerging Market Bonds', 'IEMB.L', 'A', '420', null, '0.05', '0.5', '0.0334', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'Emerging Market Local Bonds', 'IEML.L', 'A', '420', null, '0', '0.3', '0.011', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', null, '0.05', '1', '0.0134', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.05', '0.5', '0.0334', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Cash', 'Cash', 'Cash', 'A', '99999', null, '0', '1', '0.001', '0', '0', '2017-07-30 13:49:13', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Commodity', 'Precious Metals', 'IAU.N', 'A', '900', null, '0', '1', '0.0225', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.25', '0.5', '0.069', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Equity', 'Singapore Equities', 'EWS.N', 'A', '100', null, '0.05', '0.1', '0.0722', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.5', '0.75', '0.0617', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'Corporate Bonds ', 'LQDE.L', 'A', '610', null, '0.05', '1', '0.0206', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0', '0.2', '0.0264', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'Emerging Market Bonds', 'IEMB.L', 'A', '420', null, '0.05', '0.5', '0.0334', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'Emerging Market Local Bonds', 'IEML.L', 'A', '420', null, '0', '0.3', '0.011', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'Singapore Bonds', 'F00000MQNO.MSTA', 'A', '420', null, '0.25', '0.5', '0.0145', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'A', '600', null, '0.05', '1', '0.0134', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.05', '0.5', '0.0334', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.04', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'N', '110', null, '0.03', '0.07', '0.065', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.08', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.07', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'Japan Equities', 'SJPA.L', 'N', '130', null, '0.05', '0.07', '0.05', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0.04', '0.07', '0.065', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.32', '1', '0.07', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.14', '0.16', '0.05', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Fixed Income', 'Pan Asia Bonds', '2821.HK', 'A', '400', null, '0.25', '0.3', '0.03', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Fixed Income', 'Singapore Bonds', 'KV4.SI', 'A', '420', null, '0.25', '0.6', '0.022', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'N', '600', null, '0.14', '0.16', '0.022', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.13', '0.05', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Commodity', 'Precious Metals', 'GLD.N', 'A', '900', null, '0', '1', '0.04', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'Dev Asia X Japan Equities', 'IPXJ.L', 'N', '110', null, '0.03', '0.07', '0.065', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'Emerging Mkt. Equities', 'EIMI.L', 'A', '120', null, '0.22', '0.25', '0.08', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'Europe Equities', 'IMEU.L', 'A', '140', null, '0.2', '0.25', '0.07', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'Japan Equities', 'SJPA.L', 'N', '130', null, '0.05', '0.07', '0.05', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'Singapore Equities', 'ES3.SI', 'A', '100', null, '0.04', '0.07', '0.065', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Equity', 'U.S. Equities', 'VUSD.L', 'A', '150', null, '0.32', '1', '0.07', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Fixed Income', 'E.U. High Yield Bonds', 'IHYG.L', 'A', '500', null, '0.14', '0.3', '0.05', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Fixed Income', 'Singapore Bonds', 'F0HKG062UI.MSTA', 'A', '420', null, '0.25', '0.6', '0.022', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Fixed Income', 'U.S. Bonds', 'IUAG.L', 'N', '600', null, '0.14', '0.2', '0.022', '0', '0', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`sec_prime_asset_group` (`theme`, `assetclass`, `primeassetclass`, `ticker`, `status`, `sortorder`, `color`, `lowerBound`, `upperBound`, `expectedReturn`, `risk`, `yield`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Fixed Income', 'U.S. High Yield Bonds', 'IHYU.L', 'A', '610', null, '0.11', '0.2', '0.05', '0', '0', '2017-07-30 13:49:12', null);

ALTER TABLE `invdb`.`sec_rbsa` 
ADD COLUMN `style` VARCHAR(10) NULL DEFAULT NULL AFTER `sec_type`;

INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'EWS.N', 'EWS.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'F00000MQNO.MSTA', 'F00000MQNO.MSTA', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IAU.N', 'IAU.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IEMB.L', 'IEMB.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IEML.L', 'IEML.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'IVV.N', 'IVV.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'LQDE.L', 'LQDE.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'SPY.N', 'SPY.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'VUSD.L', '1306.T', '0.09', '2017-07-30', 'JPY', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'VUSD.L', 'VAS.AX', '0.03', '2017-07-30', 'AUD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'VUSD.L', 'VEUR.L', '0.25', '2017-07-30', 'GBP', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'VUSD.L', 'VUSD.L', '0.6', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB', 'VUSD.L', 'XIC.TO', '0.03', '2017-07-30', 'CAD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'EWS.N', 'EWS.N', '1', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'F00000MQNO.MSTA', 'F00000MQNO.MSTA', '1', '2017-07-30', 'SGD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', '1', '2017-07-30', 'SGD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IAU.N', 'IAU.N', '1', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IEMB.L', 'IEMB.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IEML.L', 'IEML.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'IVV.N', 'IVV.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'LQDE.L', 'LQDE.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'SPY.N', 'SPY.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'VUSD.L', '1306.T', '0.09', '2017-07-30', 'JPY', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'VUSD.L', 'VAS.AX', '0.03', '2017-07-30', 'AUD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'VUSD.L', 'VEUR.L', '0.25', '2017-07-30', 'GBP', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'VUSD.L', 'VUSD.L', '0.6', '2017-07-30', 'USD', null, 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('8.UOB.Sing', 'VUSD.L', 'XIC.TO', '0.03', '2017-07-30', 'CAD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', '2821.HK', '2821.HK', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'Cash', 'Cash', '1', '2017-07-30', 'USD', 'USD', 'USD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'ES3.SI', 'ES3.SI', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'GLD.N', 'GLD.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'IPXJ.L', 'IPXJ.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'SJPA.L', 'SJPA.L', '1', '2017-07-30', 'GBX', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB', 'VUSD.L', 'VUSD.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', '1306.T', '1306.T', '1', '2017-07-30', 'JPY', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'EIMI.L', 'EIMI.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'EWS.N', 'EWS.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'F00000MQNO.MSTA', 'F00000MQNO.MSTA', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'F0HKG062UI.MSTA', 'F0HKG062UI.MSTA', '1', '2017-07-30', 'SGD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IAU.N', 'IAU.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IEMB.L', 'IEMB.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IEML.L', 'IEML.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IHYG.L', 'IHYG.L', '1', '2017-07-30', 'EUR', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IHYU.L', 'IHYU.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IMEU.L', 'IMEU.L', '1', '2017-07-30', 'GBX', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IUAG.L', 'IUAG.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'IVV.N', 'IVV.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'KV4.SI', 'KV4.SI', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'LQDE.L', 'LQDE.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'SPY.N', 'SPY.N', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'VAS.AX', 'VAS.AX', '1', '2017-07-30', 'AUD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'VEUR.L', 'VEUR.L', '1', '2017-07-30', 'GBP', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'VUSD.L', 'VUSD.L', '1', '2017-07-30', 'USD', 'USD', 'SGD');
INSERT INTO `invdb`.`sec_rbsa` (`theme`, `primeasset_ticker`, `ticker`, `weight`, `created`, `settlecurrency`, `style`, `tradeCurrency`) VALUES ('T.8.UOB.Sing', 'XIC.TO', 'XIC.TO', '1', '2017-07-30', 'CAD', 'USD', 'SGD');


INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', '8.UOB', 'A', 'Grow Wealth', '4', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', '8.UOB.Sing', 'A', 'Grow Wealth', '3', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', 'T.8.UOB', 'N', 'Grow Wealth', '6', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', null);
INSERT INTO `invdb`.`user_basket_access` (`advisor`, `theme`, `status`, `displayname`, `sortorder`, `primary`, `taxable`, `model`, `tradeCurrency`, `created`, `lastupdated`) VALUES ('UOB', 'T.8.UOB.Sing', 'A', 'Grow Wealth', '5', 'Y', 'N', 'O', 'SGD', '2017-07-30 13:49:12', null);

Create table invdb.tmp_sec_master_uob
select * from invdb.sec_master where 1 = 2;

ALTER TABLE `invdb`.`tmp_sec_master_uob` 
ADD PRIMARY KEY (`instrumentid`);

INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('1', 'A', 'A', 'Cash', null, null, 'Cash', 'Cash', 'Cash', 'Cash', null, null, '0', null, null, '0', '', 'USD', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('13', 'A', 'A', 'IAU.N', null, null, 'IAU.N', 'iShares Gold Trust', 'Commodity', 'Gold', null, null, '0', null, null, '0', '', 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('17', 'A', 'A', 'IVV.N', null, null, 'IVV.N', 'iShares Core S&P 500', 'Equity', 'Large Cap', null, null, '0.0007', null, null, '0.10901', '', 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('23', 'A', 'A', 'JNK.N', null, null, 'JNK.N', 'SPDR Barclays High Yield Bond ETF', 'HighYield', 'Corporate Junk', null, null, '0.004', null, null, '0.041494', '', 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('35', 'A', 'A', 'SPY.N', null, null, 'SPY.N', 'SPDR S&P 500', 'Equity', 'Large Cap', null, null, '0.0009', null, null, '0.104227', '', 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('100', 'A', 'A', '2821.HK', null, null, '2821.HK', 'ABF Pan Asia Bond Index Fund', 'Fixed Income', 'Pan Asia Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('101', 'A', 'A', 'IPXJ.L', null, null, 'IPXJ.L', 'iShares MSCI Pacific ex Japan', 'Equity', 'Dev Asia X Japan Equities', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('102', 'A', 'A', 'EIMI.L', null, null, 'EIMI.L', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('103', 'A', 'A', 'IHYG.L', null, null, 'IHYG.L', 'iShares Euro High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'E.U. High Yield Bonds', null, null, '0', null, null, '0', null, 'LSE', 'EUR');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('104', 'A', 'A', 'IHYU.L', null, null, 'IHYU.L', 'iShares $ High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'U.S. High Yield Bonds', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('105', 'A', 'A', 'SJPA.L', null, null, 'SJPA.L', 'iShares Core MSCI Japan IMI UCITS ETF', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'LSE', 'GBX');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('106', 'A', 'A', 'IMEU.L', null, null, 'IMEU.L', 'iShares MSCI Europe UCITS ETF (Dist)', 'Equity', 'Europe Equities', null, null, '0', null, null, '0', null, 'LSE', 'GBX');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('107', 'A', 'A', 'IUAG.L', null, null, 'IUAG.L', 'iShares US Aggregate Bond UCITS ETF', 'Fixed Income', 'U.S. Bonds', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('111', 'A', 'A', 'EWS.N', null, null, 'EWS.N', 'iShares MSCI Singapore Capped', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('114', 'A', 'A', 'EWJ.N', null, null, 'EWJ.N', 'ISHARES CORE MSCI JAP IMI UCITS', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('117', 'A', 'A', 'VUSD.L', null, null, 'VUSD.L', 'Vanguard S&P 500 UCITS ETF', 'Equity', 'U.S. Equities', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('118', 'A', 'A', 'ES3.SI', null, null, 'ES3.SI', 'SPDR Straits Times Index ETF', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'SGX', 'SGD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('119', 'A', 'A', 'KV4.SI', null, null, 'KV4.SI', 'Markit iBoxx ABF Singapore Government UCITS ETF 1C (KV4)', 'Fixed Income', 'Singapore Bonds', null, null, '0.2', null, null, null, null, 'SGX', 'SGD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('132', 'A', 'A', 'GLD.N', null, null, 'GLD.N', 'SPDR® Gold Shares', 'Commodity', 'Precious Metals', null, null, '0.004', null, null, '0.134075', '', 'NYSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('600', 'A', 'A', 'VEUR.L', null, null, 'VEUR.L', 'VANGUARD FTSE DEV EU UCITS ETF', 'Equity', 'Europe Equities', null, null, '0', null, null, '0', null, 'LSE', 'GBP');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('601', 'A', 'A', '1306.T', null, null, '1306.T', 'TOPIX EXCHANGE TRADED', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'TSE', 'JPY');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('602', 'A', 'A', 'XIC.TO', null, null, 'XIC.TO', 'iShares Core SP TSX CA', 'Equity', 'Australian Equities', null, null, '0', null, null, '0', null, 'TSE', 'CAD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('603', 'A', 'A', 'VAS.AX', null, null, 'VAS.AX', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', null, null, '0', null, null, '0', null, 'ASX', 'AUD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('610', 'A', 'A', 'LQDE.L', null, null, 'LQDE.L', 'iShares $ Corp Bond UCITS ETF USD (Dist)', 'Fixed Income', 'Corporate Bonds', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('611', 'A', 'A', 'IEMB.L', null, null, 'IEMB.L', 'iShares J P Morgan $EM Bond ETF', 'Fixed Income', 'Emerging Market Bonds', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('612', 'A', 'A', 'IEML.L', null, null, 'IEML.L', 'iShares J P Morgan $EM Local Bond ETF', 'Fixed Income', 'Emerging Market Local Bonds', null, null, '0', null, null, '0', null, 'LSE', 'USD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('1004', 'A', 'A', 'F0HKG062UI.MSTA', null, 'SG9999003412', 'F0HKG062UI.MSTA', 'United Singapore Bond Fund', 'Fixed Income', 'Singapore Bonds', null, null, null, null, null, null, null, 'MSTA', 'SGD');
INSERT INTO `invdb`.`tmp_sec_master_uob` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('1005', 'A', 'A', 'F00000MQNO.MSTA', null, 'SG9999007454', 'F00000MQNO.MSTA', 'Eastspring Investments Unit Trusts', 'Fixed Income', 'Singapore Bonds', null, null, null, null, null, null, null, 'MSTA', 'SGD');

DELETE FROM invdb.sec_master where ticker in (select ticker from `invdb`.`tmp_sec_master_uob`);
DELETE FROM invdb.sec_master where instrumentid in (select instrumentid from `invdb`.`tmp_sec_master_uob`);

insert into invdb.sec_master 
select * from `invdb`.`tmp_sec_master_uob`;

ALTER TABLE `invdb`.`sec_asset_mapping` 
CHANGE COLUMN `sec_type` `type` VARCHAR(2) NOT NULL DEFAULT 'OT' ;
ALTER TABLE `invdb`.`sec_asset_mapping` 
ADD COLUMN `style` VARCHAR(20) NULL AFTER `type`;



INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', '1306.T', 'Equity', 'Equity Securities', '#333F50', '10', 'Japan Equities', 'Japan Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', null, '99999', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', null, '120', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'EWJ.N', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'EWS.N', 'Equity', 'Equity Securities', '#333F50', '10', 'Singapore Equities', 'Singapore Equities', null, '100', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'F00000MQNO.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'F0HKG062UI.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'GLD.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'CM', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IAU.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IEMB.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Emerging Market Bonds', 'Energing Market Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IEML.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Emerging Market Bonds', 'Energing Market Local Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', null, '500', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', null, '610', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IMEU.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IPXJ.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', null, '600', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'IVV.N', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'JNK.N', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'SPDR Barclays High Yield Bond ', 'SPDR Barclays High Yield Bond ', null, '610', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'KV4.SI', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'LQDE.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Corpoarate Bonds', 'Corporate Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'SPY.N', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'VAS.AX', 'Equity', 'Equity Securities', '#333F50', '10', 'Australian Equity', 'Australian Equities', null, '145', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'VEUR.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB', 'XIC.TO', 'Equity', 'Equity Securities', '#333F50', '10', 'Canadian Equities', 'Canadian Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', '1306.T', 'Equity', 'Equity Securities', '#333F50', '10', 'Japan Equities', 'Japan Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', null, '99999', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', null, '120', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'EWJ.N', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'EWS.N', 'Equity', 'Equity Securities', '#333F50', '10', 'Singapore Equities', 'Singapore Equities', null, '100', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'F00000MQNO.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'F0HKG062UI.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'GLD.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'CM', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IAU.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'CM', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IEMB.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Emerging Market Bonds', 'Energing Market Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IEML.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Emerging Market Bonds', 'Energing Market Local Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', null, '500', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', null, '610', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IMEU.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IPXJ.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', null, '600', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'IVV.N', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'JNK.N', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'SPDR Barclays High Yield Bond ', 'SPDR Barclays High Yield Bond ', null, '610', 'FX', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'KV4.SI', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'LQDE.L', 'Fixed Income', 'Fixed Income Securities', '#333F50', '10', 'Corpoarate Bonds', 'Corporate Bonds', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'SPY.N', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'VAS.AX', 'Equity', 'Equity Securities', '#333F50', '10', 'Australian Equity', 'Australian Equities', null, '145', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'VEUR.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('8.UOB.Sing', 'XIC.TO', 'Equity', 'Equity Securities', '#333F50', '10', 'Canadian Equities', 'Canadian Equities', null, '140', 'EQ', '2017-10-10 17:17:39', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', '2821.HK', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Pan Asia Bonds', 'Pan Asia Bonds', null, '400', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', null, '99999', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', null, '120', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'ES3.SI', 'Equity', 'Equity Securities', '#333F50', '10', 'Singapore Equities', 'Singapore Equities', null, '100', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'GLD.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', null, '500', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', null, '610', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'IMEU.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'IPXJ.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Dev Asia X Japan Equities', 'Dev Asia X Japan Equities', null, '110', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', null, '600', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'KV4.SI', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'Singapore Bonds', null, '420', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'SJPA.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Japan Equities', 'Japan Equities', null, '130', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'Cash', 'Cash', 'Cash', '#8E8E8E', '40', 'Cash', 'Cash', null, '99999', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'EIMI.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Emerging Mkt. Equities', 'Emerging Mkt. Equities', null, '120', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'ES3.SI', 'Equity', 'Equity Securities', '#333F50', '10', 'Singapore Equities', 'Singapore Equities', null, '100', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'F0HKG062UI.MSTA', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'Singapore Bonds', 'United Singapore Bond Funds', null, '420', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'GLD.N', 'Commodity', 'Commodities', '#5E5E5E', '30', 'Precious Metals', 'Precious Metals', null, '900', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'IHYG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'E.U. High Yield Bonds', 'E.U. High Yield Bonds', null, '500', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'IHYU.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. High Yield Bonds', 'U.S. High Yield Bonds', null, '610', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'IMEU.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Europe Equities', 'Europe Equities', null, '140', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'IPXJ.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Dev Asia X Japan Equities', 'Dev Asia X Japan Equities', null, '110', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'IUAG.L', 'Fixed Income', 'Fixed Income Securities', '#47566D', '20', 'U.S. Bonds', 'U.S. Bonds', null, '600', 'FX', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'SJPA.L', 'Equity', 'Equity Securities', '#333F50', '10', 'Japan Equities', 'Japan Equities', null, '130', 'EQ', '2017-07-30 22:54:47', null, '');
INSERT INTO `invdb`.`sec_asset_mapping` (`theme`, `ticker`, `assetclass`, `assetName`, `assetcolor`, `assetsortorder`, `subclass`, `subclassName`, `subclasscolor`, `subclasssortorder`, `type`, `style`, `created`, `lastUpdated`) VALUES ('T.8.UOB.Sing', 'VUSD.L', 'Equity', 'Equity Securities', '#333F50', '10', 'U.S. Equities', 'U.S. Equities', null, '150', 'EQ', '2017-07-30 22:54:47', null, '');
