DROP TABLE IF EXISTS `fees_charged`;

CREATE TABLE `fees_charged` (
  `clientAccountID` varchar(20) NOT NULL,
  `processed` varchar(1) DEFAULT 'N',
  `fromDate` varchar(8) NOT NULL,
  `toDate` varchar(8) NOT NULL,
  `firstBusinessDate` varchar(8) NOT NULL,
  `lastBusinessDate` varchar(8) NOT NULL,
  `billingYear` varchar(4) NOT NULL,
  `advisor` varchar(30) NOT NULL,
  `cash` double DEFAULT '0',
  `invested` double DEFAULT '0',
  `priorfromDate` varchar(8) DEFAULT NULL,
  `priortoDate` varchar(8) DEFAULT NULL,
  `priorcash` double DEFAULT '0',
  `priorinvested` double DEFAULT '0',
  `billingDays` int(11) DEFAULT '0',
  `commission` double DEFAULT '0',
  `otherFee` double DEFAULT '0',
  `invessenceFee` double DEFAULT '0',
  `advisorFee` double DEFAULT '0',
  `totalAdvisorFee` double DEFAULT '0',
  `invoiceFee` double DEFAULT '0',
  `ytdcommission` double DEFAULT '0',
  `ytdotherFee` double DEFAULT '0',
  `ytdinvessenceFee` double DEFAULT '0',
  `ytdAdvisorFee` double DEFAULT '0',
  `ytdtotalAdvisorFee` double DEFAULT '0',
  `ytdinvoiceFee` double DEFAULT '0',
  `datecreated` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`clientAccountID`,`fromDate`,`toDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
