delimiter $$

CREATE TABLE `ticker_information` (
  `TICKER` varchar(20) DEFAULT NULL,
  `TRADE_DATE` varchar(20) DEFAULT NULL,
  `LAST_PRICE` varchar(20) DEFAULT NULL,
  `BOOK_VALUE` varchar(20) DEFAULT NULL,
  `EPS_CURRENT` varchar(20) DEFAULT NULL,
  `MARKET_CAP` varchar(20) DEFAULT NULL,
  `OPENDATE` varchar(20) DEFAULT NULL,
  `EXDIVIDENT_DATE` varchar(20) DEFAULT NULL,
  `PRICE_EPS` varchar(20) DEFAULT NULL,
  `DIVIDENT` varchar(20) DEFAULT NULL,
  `AVG_DAILY_VOL` varchar(20) DEFAULT NULL,
  `DIVIDENT_SHARE` varchar(20) DEFAULT NULL,
  `EARNING_SHARE` varchar(20) DEFAULT NULL,
  `EPS_NEXT` varchar(20) DEFAULT NULL,
  `PREV_CLOSE` varchar(20) DEFAULT NULL,
  `PRICE_SALES` varchar(20) DEFAULT NULL,
  `PE_RATIO` varchar(20) DEFAULT NULL,
  `PEG_RATIO` varchar(20) DEFAULT NULL,
  `YR_TARGET_PRICE` varchar(20) DEFAULT NULL,
  `EPS_NEXTQ` varchar(20) DEFAULT NULL,
  `EBITDA` varchar(20) DEFAULT NULL,
  `PRICE_BOOK` varchar(20) DEFAULT NULL,
  `DIVIDENT_PAYDATE` varchar(20) DEFAULT NULL,
  `PRICE_EPS_YR` varchar(20) DEFAULT NULL,
  `VOLUME` varchar(20) DEFAULT NULL,
  `XCHANGE` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

CREATE
TRIGGER `tr_add_to_sec_daily_info`
AFTER INSERT ON `ticker_information`
FOR EACH ROW
BEGIN
   CALL  `sp_sec_daily_info_add_mod`
	( 'A', NEW.`TICKER`, STR_TO_DATE(NEW.`TRADE_DATE`,'%m/%d/%Y'), NEW.`LAST_PRICE`, NEW.`VOLUME`);

 END
$$

