INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'CC_EXTERNAL_RECEIVER', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'CC_INVESSENCE_RECEIVER', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'HOST', 'smtp.gmail.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'L1_SUPPORT_EMAIL', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'L2_SUPPORT_EMAIL', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'LOCAL_SRC_DIRECTORY', 'C:/UOB/data/acctOpenfiles', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PASSWORD', 'G3n3r@l89', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PDF_FILES_CUST_DIRECTORY', 'D:/data1/pdf/UOB/customerFiles/', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PDF_FILES_MASTER_DIRECTORY', 'D:/data1/pdf/UOB/masterFiles/', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PORT', '587', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'SENDER_EMAIL', 'no-reply@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'SFTP_SRC_DIRECTORY', '/data/download/UOB/acctOpenfiles', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'USERNAME', 'no-reply@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('DEV', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'ZIP_FILES_DIRECTORY', 'D:/data1/pdf/UOB/zipFiles/', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'CC_EXTERNAL_RECEIVER', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'CC_INVESSENCE_RECEIVER', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'HOST', 'smtp.gmail.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'L1_SUPPORT_EMAIL', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'L2_SUPPORT_EMAIL', 'abhangp@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'LOCAL_SRC_DIRECTORY', 'C:/UOB/data/acctOpenfiles', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PASSWORD', 'G3n3r@l89', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PDF_FILES_CUST_DIRECTORY', '/data/pdf/UOB/customerFiles/', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PDF_FILES_MASTER_DIRECTORY', '/data/pdf/UOB/masterFiles/', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'PORT', '587', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'SENDER_EMAIL', 'no-reply@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'SFTP_SRC_DIRECTORY', '/data/download/UOB/acctOpenfiles', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'USERNAME', 'no-reply@invessence.com', 'N', '2017-11-16 11:10:02');
INSERT INTO `service`.`service_config_details` (`mode`, `company`, `service`, `vendor`, `name`, `value`, `encrFlag`, `created`) VALUES ('UAT', 'UOB', 'DOCUMENT-SERVICES', 'iText', 'ZIP_FILES_DIRECTORY', '/data/pdf/UOB/zipFiles/', 'N', '2017-11-16 11:10:02');



INSERT INTO `service`.`service_master` (`company`, `service`, `status`, `vendor`) VALUES ('UOB', 'DOCUMENT-SERVICES', 'A', 'iTEXT');



INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `refValue`) VALUES ('UOB', 'DOCUMENT-SERVICES', 'ACCT_OPEN_EXISTING_USER', 'iText', 'A', 'UOB_ACCT_OPEN_EXISTING_USER');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `refValue`) VALUES ('UOB', 'DOCUMENT-SERVICES', 'ACCT_OPEN_NEW_USER', 'iText', 'A', 'UOB_ACCT_OPEN_NEW_USER');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `refValue`) VALUES ('UOB', 'DOCUMENT-SERVICES', 'GUIDE_CAUTIONARY_NOTES', 'iText', 'A', 'UOB_GUIDE_CAUTIONARY_NOTES');
INSERT INTO `service`.`service_operation_details` (`company`, `service`, `operation`, `vendor`, `status`, `refValue`) VALUES ('UOB', 'DOCUMENT-SERVICES', 'RISK_DISC_STATEMENT', 'iText', 'A', 'UOB_RISK_DISC_STATEMENT');
