DROP PROCEDURE IF EXISTS `sav_user_risk_questions`;

DELIMITER $$
CREATE PROCEDURE `sav_user_risk_questions`(
	IN	p_acctnum	bigint(20),
	IN  p_investmentgoal VARCHAR(20),
	IN	p_age	tinyint,
	IN	p_retireage	tinyint,
	IN	p_retired	tinyint,
    IN	p_horizon	tinyint,
	IN	p_ans1	tinyint,
	IN	p_ans2	tinyint,
	IN	p_ans3	tinyint,
	IN	p_ans4	tinyint,
	IN	p_ans5	tinyint,
	IN	p_ans6	tinyint,
	IN	p_ans7	tinyint,
	IN	p_ans8	tinyint,
	IN	p_ans9	tinyint,
	IN	p_ans10	tinyint,
	IN	p_ans11	tinyint,
	IN	p_ans12	tinyint,
	IN	p_ans13	tinyint,
	IN	p_ans14	tinyint,
	IN	p_ans15	tinyint,
	IN	p_formula	varchar(1),
	IN	p_r1	tinyint,
	IN	p_r2	tinyint,
	IN	p_r3	tinyint,
	IN	p_r4	tinyint,
	IN	p_r5	tinyint,
	IN	p_r6	tinyint,
	IN	p_r7	tinyint,
	IN	p_r8	tinyint,
	IN	p_r9	tinyint,
	IN	p_r10	tinyint,
	IN	p_r11	tinyint,
	IN	p_r12	tinyint,
	IN	p_r13	tinyint,
	IN	p_r14	tinyint,
	IN	p_r15	tinyint,
	IN	p_totalRisk	tinyint
)
BEGIN 

			INSERT INTO `user_risk_questions`
			(
			`acctnum`,
			`investmentgoal`,
			`age`,
			`retireage`,
			`retired`,
			`horizon`,
			`ans1`,
			`ans2`,
			`ans3`,
			`ans4`,
			`ans5`,
			`ans6`,
			`ans7`,
			`ans8`,
			`ans9`,
			`ans10`,
			`ans11`,
			`ans12`,
			`ans13`,
			`ans14`,
			`ans15`,
            `formula`,
			`risk1`,
			`risk2`,
			`risk3`,
			`risk4`,
			`risk5`,
			`risk6`,
			`risk7`,
			`risk8`,
			`risk9`,
			`risk10`,
			`risk11`,
			`risk12`,
			`risk13`,
			`risk14`,
			`risk15`,
			`totalrisk`,
			`created`,
			`lastUpdated`)
			VALUES (
				p_acctnum,
                p_investmentgoal,
				p_age,
				p_retired,
                p_retired,
				p_horizon,
				p_ans1,
				p_ans2,
				p_ans3,
				p_ans4,
				p_ans5,
				p_ans6,
				p_ans7,
				p_ans8,
				p_ans9,
				p_ans10,
				p_ans11,
				p_ans12,
				p_ans13,
				p_ans14,
				p_ans15,
				p_formula,
				p_r1,
				p_r2,
				p_r3,
				p_r4,
				p_r5,
				p_r6,
				p_r7,
				p_r8,
				p_r9,
				p_r10,
				p_r11,
				p_r12,
				p_r13,
				p_r14,
				p_r15,
				p_totalRisk,
				now(),
				null
                )
                ON DUPLICATE KEY UPDATE
                `investmentgoal` = p_investmentgoal,
				`age`	 =	p_age	,
				`retireage`	 =	p_retireage	,
				`retired`	 =	p_retired	,
				`horizon`=	p_horizon	,
				`ans1`	 =	p_ans1	,
				`ans2`	 =	p_ans2	,
				`ans3`	 =	p_ans3	,
				`ans4`	 =	p_ans4	,
				`ans5`	 =	p_ans5	,
				`ans6`	 =	p_ans6	,
				`ans7`	 =	p_ans7	,
				`ans8`	 =	p_ans8	,
				`ans9`	 =	p_ans9	,
				`ans10`	 =	p_ans10	,
				`ans11`	 =	p_ans11	,
				`ans12`	 =	p_ans12	,
				`ans13`	 =	p_ans13	,
				`ans14`	 =	p_ans14	,
				`ans15`	 =	p_ans15	,
				`formula`=	p_formula	,
				`risk1`	 =	p_r1	,
				`risk2`=	p_r2	,
				`risk3`	 =	p_r3	,
				`risk4`	 =	p_r4	,
				`risk5`	 =	p_r5	,
				`risk6`	 =	p_r6	,
				`risk7`	 =	p_r7	,
				`risk8`	 =	p_r8	,
				`risk9`	 =	p_r9	,
				`risk10`	 =	p_r10	,
				`risk11` =	p_r11	,
				`risk12` =	p_r12	,
				`risk13` =	p_r13	,
				`risk14` =	p_r14	,
				`risk15` =	p_r15	,
				`totalRisk`=p_totalRisk	,
				`lastupdated` = now()
                ;


END$$
DELIMITER ;
