## Script for inserting data into download_files of temp schema


SET SQL_SAFE_UPDATES = 0;
delete from temp.download_files;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRD', '1', 'Y', 'tmp_td_demographic', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'N', 'Y', 'N', 'DB', 'sp_upload_td_demographic', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'SEC', '2', 'Y', 'tmp_td_security', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'Y', 'N', 'N', 'DB', 'sp_upload_td_sec_master', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'PRI', '3', 'Y', 'tmp_td_price', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'Y', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'POS', '4', 'Y', 'tmp_td_position', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRN', '5', 'Y', 'tmp_td_transaction', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'CBL', '6', 'Y', 'tmp_td_unrealized', 'DAILY', '/data/download/tcm/AGWQ', '/data/eodfiles/tcm/AGWQ', 'csv', 'Y', 'N', 'N', 'DB', 'sp_upload_td_unrealized', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRD', '7', 'Y', 'tmp_td_demographic', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'Y', 'N', 'DB', 'sp_upload_td_demographic', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'SEC', '8', 'Y', 'tmp_td_security', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'Y', 'DB', 'sp_upload_td_sec_master', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'PRI', '9', 'Y', 'tmp_td_price', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'Y', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'POS', '10', 'Y', 'tmp_td_position', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRN', '11', 'Y', 'tmp_td_transaction', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'CBL', '12', 'Y', 'tmp_td_unrealized', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'N', 'DB', 'sp_upload_td_unrealized', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRD', '13', 'Y', 'tmp_td_demographic', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'Y', 'N', 'DB', 'sp_upload_td_demographic', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'SEC', '14', 'Y', 'tmp_td_security', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'Y', 'DB', 'sp_upload_td_sec_master', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'PRI', '15', 'Y', 'tmp_td_price', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'Y', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'POS', '16', 'Y', 'tmp_td_position', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRN', '17', 'Y', 'tmp_td_transaction', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'N', 'DB', '', now(), 'N', '1', 'csv');
INSERT INTO temp.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, canbedups, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'CBL', '18', 'Y', 'tmp_td_unrealized', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'N', 'DB', 'sp_upload_td_unrealized', now(), 'N', '1', 'csv');
