DROP TABLE IF EXISTS `cash_report`;

CREATE TABLE `cash_report` (
		clientAccountID	VARCHAR(20)	NOT NULL
	,	accountAlias	VARCHAR(20)	DEFAULT NULL
	,	currencyPrimary	VARCHAR(20)	DEFAULT NULL
	,	fromDate	VARCHAR(10)	NOT NULL
	,	toDate	VARCHAR(10)	NOT NULL
	,	startingCash	Double	DEFAULT NULL
	,	startingCashSecurities	Double	DEFAULT NULL
	,	startingCashCommodities	Double	DEFAULT NULL
	,	commissions	Double	DEFAULT NULL
	,	commissionsSecurities	Double	DEFAULT NULL
	,	commissionsCommodities	Double	DEFAULT NULL
	,	commissionsMTD	Double	DEFAULT NULL
	,	commissionsYTD	Double	DEFAULT NULL
	,	deposit_Withdrawals	Double	DEFAULT NULL
	,	deposit_WithdrawalsSecurities	Double	DEFAULT NULL
	,	deposit_WithdrawalsCommodities	Double	DEFAULT NULL
	,	deposit_WithdrawalsMTD	Double	DEFAULT NULL
	,	deposit_WithdrawalsYTD	Double	DEFAULT NULL
	,	deposits	Double	DEFAULT NULL
	,	depositsSecurities	Double	DEFAULT NULL
	,	depositsCommodities	Double	DEFAULT NULL
	,	depositsMTD	Double	DEFAULT NULL
	,	depositsYTD	Double	DEFAULT NULL
	,	withdrawals	Double	DEFAULT NULL
	,	withdrawalsSecurities	Double	DEFAULT NULL
	,	withdrawalsCommodities	Double	DEFAULT NULL
	,	withdrawalsMTD	Double	DEFAULT NULL
	,	withdrawalsYTD	Double	DEFAULT NULL
	,	accountTransfers	Double	DEFAULT NULL
	,	accountTransfersSecurities	Double	DEFAULT NULL
	,	accountTransfersCommodities	Double	DEFAULT NULL
	,	accountTransfersMTD	Double	DEFAULT NULL
	,	accountTransfersYTD	Double	DEFAULT NULL
	,	internalTransfers	Double	DEFAULT NULL
	,	internalTransfersSecurities	Double	DEFAULT NULL
	,	internalTransfersCommodities	Double	DEFAULT NULL
	,	internalTransfersMTD	Double	DEFAULT NULL
	,	internalTransfersYTD	Double	DEFAULT NULL
	,	dividends	Double	DEFAULT NULL
	,	dividendsSecurities	Double	DEFAULT NULL
	,	dividendsCommodities	Double	DEFAULT NULL
	,	dividendsMTD	Double	DEFAULT NULL
	,	dividendsYTD	Double	DEFAULT NULL
	,	brokerInterest	Double	DEFAULT NULL
	,	brokerInterestSecurities	Double	DEFAULT NULL
	,	brokerInterestCommodities	Double	DEFAULT NULL
	,	brokerInterestMTD	Double	DEFAULT NULL
	,	brokerInterestYTD	Double	DEFAULT NULL
	,	bondInterest	Double	DEFAULT NULL
	,	bondInterestSecurities	Double	DEFAULT NULL
	,	bondInterestCommodities	Double	DEFAULT NULL
	,	bondInterestMTD	Double	DEFAULT NULL
	,	bondInterestYTD	Double	DEFAULT NULL
	,	cashSettlingMtm	Double	DEFAULT NULL
	,	cashSettlingMtmSecurities	Double	DEFAULT NULL
	,	cashSettlingMtmCommodities	Double	DEFAULT NULL
	,	cashSettlingMtmMTD	Double	DEFAULT NULL
	,	cashSettlingMtmYTD	Double	DEFAULT NULL
	,	netTradesSales	Double	DEFAULT NULL
	,	netTradesSalesSecurities	Double	DEFAULT NULL
	,	netTradesSalesCommodities	Double	DEFAULT NULL
	,	netTradesSalesMTD	Double	DEFAULT NULL
	,	netTradesSalesYTD	Double	DEFAULT NULL
	,	netTradesPurchases	Double	DEFAULT NULL
	,	netTradesPurchasesSecurities	Double	DEFAULT NULL
	,	netTradesPurchasesCommodities	Double	DEFAULT NULL
	,	netTradesPurchasesMTD	Double	DEFAULT NULL
	,	netTradesPurchasesYTD	Double	DEFAULT NULL
	,	advisorFees	Double	DEFAULT NULL
	,	advisorFeesSecurities	Double	DEFAULT NULL
	,	advisorFeesCommodities	Double	DEFAULT NULL
	,	advisorFeesMTD	Double	DEFAULT NULL
	,	advisorFeesYTD	Double	DEFAULT NULL
	,	otherFees	Double	DEFAULT NULL
	,	otherFeesSecurities	Double	DEFAULT NULL
	,	otherFeesCommodities	Double	DEFAULT NULL
	,	otherFeesMTD	Double	DEFAULT NULL
	,	otherFeesYTD	Double	DEFAULT NULL
	,	paymentInLieu	Double	DEFAULT NULL
	,	paymentInLieuSecurities	Double	DEFAULT NULL
	,	paymentInLieuCommodities	Double	DEFAULT NULL
	,	paymentInLieuMTD	Double	DEFAULT NULL
	,	paymentInLieuYTD	Double	DEFAULT NULL
	,	transactionTax	Double	DEFAULT NULL
	,	transactionTaxSecurities	Double	DEFAULT NULL
	,	transactionTaxCommodities	Double	DEFAULT NULL
	,	transactionTaxMTD	Double	DEFAULT NULL
	,	transactionTaxYTD	Double	DEFAULT NULL
	,	withholdingTax	Double	DEFAULT NULL
	,	withholdingTaxSecurities	Double	DEFAULT NULL
	,	withholdingTaxCommodities	Double	DEFAULT NULL
	,	withholdingTaxMTD	Double	DEFAULT NULL
	,	withholdingTaxYTD	Double	DEFAULT NULL
	,	salesTax	Double	DEFAULT NULL
	,	salesTaxSecurities	Double	DEFAULT NULL
	,	salesTaxCommodities	Double	DEFAULT NULL
	,	salesTaxMTD	Double	DEFAULT NULL
	,	salesTaxYTD	Double	DEFAULT NULL
	,	fXTranslationGain_Loss	Double	DEFAULT NULL
	,	fXTranslationGain_LossSecurities	Double	DEFAULT NULL
	,	fXTranslationGain_LossCommodities	Double	DEFAULT NULL
	,	endingCash	Double	DEFAULT NULL
	,	endingCashSecurities	Double	DEFAULT NULL
	,	endingCashCommodities	Double	DEFAULT NULL
	,	endingSettledCash	Double	DEFAULT NULL
	,	endingSettledCashSecurities	Double	DEFAULT NULL
	,	endingSettledCashCommodities	Double	DEFAULT NULL
  , PRIMARY KEY (`clientAccountID`,`fromDate`,`toDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
