delimiter $$

CREATE TABLE `client_info` (
  `acctnum` bigint(20) NOT NULL AUTO_INCREMENT,
  `logonid` varchar(20) NOT NULL,
  `prefix` varchar(25) DEFAULT NULL,
  `lastname` varchar(45) DEFAULT NULL,
  `middlename` varchar(25) DEFAULT NULL,
  `firstname` varchar(45) DEFAULT NULL,
  `suffix` varchar(25) DEFAULT NULL,
  `address` varchar(80) DEFAULT NULL,
  `address2` varchar(30) DEFAULT NULL,
  `city` varchar(25) DEFAULT NULL,
  `state` varchar(20) DEFAULT NULL,
  `country` varchar(20) DEFAULT NULL,
  `zip` varchar(9) DEFAULT NULL,
  `addressalt` varchar(80) DEFAULT NULL,
  `address2alt` varchar(30) DEFAULT NULL,
  `cityalt` varchar(25) DEFAULT NULL,
  `statealt` varchar(20) DEFAULT NULL,
  `countryalt` varchar(20) DEFAULT NULL,
  `zipalt` varchar(9) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `maritalstatus` varchar(45) DEFAULT NULL,
  `dependents` varchar(10) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `citizenship` varchar(45) DEFAULT NULL,
  `ssn` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`acctnum`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COMMENT='			'$$


`city`,
`state`,
`country`,
`zip`,
`addressalt`,
`address2alt`,
`cityalt`,
`statealt`,
`countryalt`,
`zipalt`,
`dob`,
`maritalstatus`,
`dependents`,
`gender`,
`citizenship`,
`ssn`)
VALUES
(
<{acctnum: }>,
<{logonid: }>,
<{prefix: }>,
<{lastname: }>,
<{middlename: }>,
<{firstname: }>,
<{suffix: }>,
<{address: }>,
<{address2: }>,
<{city: }>,
<{state: }>,
<{country: }>,
<{zip: }>,
<{addressalt: }>,
<{address2alt: }>,
<{cityalt: }>,
<{statealt: }>,
<{countryalt: }>,
<{zipalt: }>,
<{dob: }>,
<{maritalstatus: }>,
<{dependents: }>,
<{gender: }>,
<{citizenship: }>,
<{ssn: }>
);