DROP TABLE IF EXISTS `performance_info`;

CREATE TABLE `performance_info` (
  `clientAccountID`		varchar(20) NOT NULL,
  `reportDate`			varchar(8) NOT NULL,
  `reportDate_prev`		varchar(8),
  `reportDate_bom`		varchar(8),
  `reportDate_boy`		varchar(8),
  `daily_divident`		double,
  `daily_deposit`		double,
  `daily_withdrawl`		double,
  `daily_unrealized`	double,
  `daily_realized`		double,
  `daily_nav_cash`		double,
  `daily_nav_stock`		double,
  `daily_nav_cash_prior` double,
  `daily_nav_stock_prior` double,
  `daily_performance`	double,
  `mtd_divident`		double,
  `mtd_deposit`			double,
  `mtd_withdrawl`		double,
  `mtd_unrealized`		double,
  `mtd_realized`		double,
  `bom_nav_cash`		double,
  `bom_nav_stock`		double,
  `mtd_performance`		double,
  `ytd_divident`		double,
  `ytd_deposit`			double,
  `ytd_withdrawl`		double,
  `ytd_unrealized`		double,
  `ytd_realized`		double,
  `boy_nav_cash`		double,
  `boy_nav_stock`		double,
  `ytd_performance`		double,
  `created`				date DEFAULT NULL,
  `lastUpdated`			date DEFAULT NULL,
  PRIMARY KEY (`clientAccountID`,`reportDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
