CREATE TABLE `sec_master` (
  `instrumentid` bigint(20) NOT NULL,
  `status` varchar(1) DEFAULT 'A' COMMENT 'Status\\\\\\\\\\\\\\\\nA - Active\\\\\\\\\\\\\\\\nM - Matured\\\\\\\\\\\\\\\\nI - Inactive\\\\\\\\\\\\\\\\nD - Defaulted\\\\\\\\\\\\\\\\nS - Split\\\\\\\\\\\\\\\\nR - Reverse Split\\\\\\\\\\\\\\\\n',
  `ticker` varchar(20) NOT NULL,
  `cusip` varchar(12) DEFAULT NULL,
  `isin` varchar(15) DEFAULT NULL,
  `name` varchar(60) DEFAULT NULL,
  `primarymarket` varchar(10) DEFAULT NULL,
  `type` varchar(12) DEFAULT NULL COMMENT 'Type of Instrument:\\\\\\\\\\\\\\\\nEquity\\\\\\\\\\\\\\\\nBond\\\\\\\\\\\\\\\\nCash',
  `subtype` varchar(20) DEFAULT NULL COMMENT 'Sub Type:\\\\\\\\\\\\\\\\nEquityDivident\\\\\\\\\\\\\\\\nEquityValue\\\\\\\\\\\\\\\\nBondTNote\\\\\\\\\\\\\\\\nBondTBill\\\\\\\\\\\\\\\\nBondTips\\\\\\\\\\\\\\\\netc...',
  `style` varchar(30) DEFAULT NULL COMMENT 'Sub Type:\\\\\\\\\\\\\\\\nEquityDivident\\\\\\\\\\\\\\\\nEquityValue\\\\\\\\\\\\\\\\nBondTNote\\\\\\\\\\\\\\\\nBondTBill\\\\\\\\\\\\\\\\nBondTips\\\\\\\\\\\\\\\\netc...',
  `assetclass` varchar(20) DEFAULT NULL COMMENT 'LargeCap\\\\\\\\\\\\\\\\nSmallCap\\\\\\\\\\\\\\\\nMidCap\\\\\\\\\\\\\\\\nBlend\\\\\\\\\\\\\\\\n',
  `subclass` varchar(20) DEFAULT NULL COMMENT 'Divident\\\\\\\\\\\\\\\\nValue\\\\\\\\\\\\\\\\nETF\\\\\\\\\\\\\\\\nSector\\\\\\\\\\\\\\\\nForeign\\\\\\\\\\\\\\\\n',
  `region` varchar(5) DEFAULT NULL COMMENT 'US\\\\\\\\\\\\\\\\nBroad',
  `region_specific` varchar(30) DEFAULT NULL COMMENT 'North America',
  `expenseRatio` double DEFAULT NULL,
  `lowerBoundReturn` double DEFAULT NULL,
  `upperBoundReturn` double DEFAULT NULL,
  `taxableReturn` double DEFAULT NULL,
  `nontaxableReturn` double DEFAULT NULL,
  `inception` date DEFAULT NULL,
  `issuer` varchar(20) DEFAULT NULL,
  `adv3months` double DEFAULT NULL,
  `aum` double DEFAULT NULL,
  `beta` double DEFAULT NULL,
  `securityRiskSTD` double DEFAULT NULL,
  `lb1` double DEFAULT NULL,
  `lb2` double DEFAULT NULL,
  `lb3` double DEFAULT NULL,
  `lb4` double DEFAULT NULL,
  `lb5` double DEFAULT NULL,
  `lb6` double DEFAULT NULL,
  `lb7` double DEFAULT NULL,
  `lb8` double DEFAULT NULL,
  `lb9` double DEFAULT NULL,
  `lb10` double DEFAULT NULL,
  `ub1` double DEFAULT NULL,
  `ub2` double DEFAULT NULL,
  `ub3` double DEFAULT NULL,
  `ub4` double DEFAULT NULL,
  `ub5` double DEFAULT NULL,
  `ub6` double DEFAULT NULL,
  `ub7` double DEFAULT NULL,
  `ub8` double DEFAULT NULL,
  `ub9` double DEFAULT NULL,
  `ub10` double DEFAULT NULL,
  PRIMARY KEY (`instrumentid`),
  UNIQUE KEY `InstrID_UNIQUE` (`instrumentid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
