use service;

DROP TABLE IF EXISTS `pdf_file_details`;
CREATE TABLE `pdf_file_details` (
  `vendor` varchar(20) NOT NULL,
  `fileName` varchar(100) NOT NULL,
  `fileId` varchar(45) NOT NULL,
  `fileExtension` varchar(10) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `active` varchar(1) NOT NULL DEFAULT 'N',
  `fileNameAppender` varchar(20) DEFAULT NULL,
  `appenderType` varchar(20) DEFAULT NULL,
  `appenderFormat` varchar(20) DEFAULT NULL,
  `available` varchar(7) DEFAULT NULL,
  `sourceDir` varchar(80) DEFAULT NULL COMMENT 'Local Directory',
  `uploadDir` varchar(80) DEFAULT NULL COMMENT 'SFTP Server Directory',
  `isPwdProtected` varchar(1) DEFAULT 'N',
  `pwdRules` varchar(10) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `lastupdated` datetime DEFAULT NULL,
  PRIMARY KEY (`vendor`,`fileName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `service`.`pdf_file_details` (`vendor`, `fileName`, `fileId`, `fileExtension`, `description`, `active`, `isPwdProtected`) VALUES ('UOB', 'APPLICATION TO OPEN ROBO ADVISOR ACCOUNT - EXISTING USER', 'UOB_ACCT_OPEN_EXISTING_USER', 'pdf', 'UOBKH Individual & Joint Application for ROBO Advisor Account _Existing Client_ 27 Oct 2017', 'A', 'N');
INSERT INTO `service`.`pdf_file_details` (`vendor`, `fileName`, `fileId`, `fileExtension`, `description`, `active`, `isPwdProtected`) VALUES ('UOB', 'APPLICATION TO OPEN ROBO ADVISOR ACCOUNT - NEW USER', 'UOB_ACCT_OPEN_NEW_USER', 'pdf', 'UOBKH Individual & Joint Application for ROBO Advisor Account _New Client_ 27 Oct 2017', 'A', 'N');
INSERT INTO `service`.`pdf_file_details` (`vendor`, `fileName`, `fileId`, `fileExtension`, `description`, `active`, `isPwdProtected`) VALUES ('UOB', 'Guide and Cautionary Notes', 'UOB_GUIDE_CAUTIONARY_NOTES', 'pdf', 'Guide and Cautionary Notes', 'I', 'N');
INSERT INTO `service`.`pdf_file_details` (`vendor`, `fileName`, `fileId`, `fileExtension`, `description`, `active`, `isPwdProtected`) VALUES ('UOB', 'Risk Disclosure Statements 27 Oct 2017', 'UOB_RISK_DISC_STATEMENT', 'pdf', 'Risk Disclosure Statements 27 Oct 2017', 'I', 'N');




DROP TABLE IF EXISTS `pdf_file_rules`;
CREATE TABLE `pdf_file_rules` (
  `fileId` varchar(45) NOT NULL,
  `dataField` varchar(45) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `pageNo` int(2) DEFAULT NULL,
  `xcord` float DEFAULT NULL,
  `ycord` float DEFAULT NULL,
  `length` int(5) DEFAULT NULL,
  `dbColumn` varchar(45) DEFAULT NULL,
  `role` varchar(45) DEFAULT NULL,
  `isRequired` varchar(1) DEFAULT 'N',
  `needToEncrypt` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`fileId`,`dataField`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'acctTypeId', 'Type of Account', '4', '230', '30', 'acctTypeId', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'controlOverUOBAcct', 'any trading account', '4', '230', '30', 'controlOverUOBAcct', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'controlOverUOBAcctName1', 'Account Name1', '4', '230', '30', 'controlOverUOBAcctName1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'controlOverUOBAcctName2', 'Account Name2', '4', '230', '30', 'controlOverUOBAcctName2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'controlOverUOBAcctNumber1', 'Account No.1', '4', '230', '30', 'controlOverUOBAcctNumber1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'controlOverUOBAcctNumber2', 'Account No.2', '4', '230', '30', 'controlOverUOBAcctNumber2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'dbCOlumn', 'description', '4', '230', '30', 'dbCOlumn', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'employerCity,employerState', 'City / State', '4', '230', '30', 'employerCity,employerState', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'employerStreetAddress4', 'Employer Address', '2', '230', '132', '1', 'employerStreetAddress4', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'faxNumber', 'Fax No.', '4', '230', '30', 'faxNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'investmentObjectives', 'investmentObjectives', '4', '230', '30', 'investmentObjectives', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'investmentObjectiveSpecify', 'investmentObjectiveSpecify', '4', '230', '30', 'investmentObjectiveSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointannualIncome', 'jointAnnual Income', '4', '230', '30', 'annualIncome', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointareYouUnableToPayYouDebts ', 'jointAreYouUnableToPayYouDebts ', '4', '230', '30', 'areYouUnableToPayYouDebts ', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointareYouUnableToPayYouDebtsDescribe', 'jointAreYouUnableToPayYouDebtsDescribe', '4', '230', '30', 'areYouUnableToPayYouDebtsDescribe', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcontrolOverUOBAcct', 'jointany trading account', '4', '230', '30', 'controlOverUOBAcct', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcontrolOverUOBAcctName1', 'jointAccount Name1', '4', '230', '30', 'controlOverUOBAcctName1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcontrolOverUOBAcctName2', 'jointAccount Name2', '4', '230', '30', 'controlOverUOBAcctName2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcontrolOverUOBAcctNumber1', 'jointAccount No.1', '4', '230', '30', 'controlOverUOBAcctNumber1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcontrolOverUOBAcctNumber2', 'jointAccount No.2', '4', '230', '30', 'controlOverUOBAcctNumber2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcountryOfBirth', 'jointCountry of Birth', '1', '230', '64', '1', 'countryOfBirth', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointcountryOfBirthSpecify', 'jointCountry of Birth Other Specify', '1', '230', '1', '1', 'countryOfBirthSpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointdob', 'jointDate of Birth (DD/MM/YYYY)', '4', '230', '475', 'dob', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointdoYouHaveAnyDisputedAccount', 'jointDoYouHaveAnyDisputedAccount', '4', '230', '30', 'doYouHaveAnyDisputedAccount', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointdoYouHaveAnyDisputedAccountDescribe', 'jointDoYouHaveAnyDisputedAccountDescribe', '4', '230', '30', 'doYouHaveAnyDisputedAccountDescribe', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerCityEmployerState', 'jointCity / State', '2', '230', '116', '1', 'employerCity', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerName', 'jointName of Employer', '4', '230', '215', 'employerName', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerStreetAddress1', 'jointEmployer Address', '4', '230', '200', 'employerStreetAddress1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerStreetAddress2', 'jointEmployer Address', '4', '230', '200', 'employerStreetAddress2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerStreetAddress3', 'jointEmployer Address', '4', '230', '200', 'employerStreetAddress3', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerStreetAddress4', 'jointEmployer Address', '4', '230', '200', 'employerStreetAddress4', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerZipCode', 'jointPostal Code', '4', '230', '185', 'employerZipCode', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointemployerZipCountry', 'jointCountry', '4', '230', '170', 'employerZipCountry', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointfatherName', 'jointFather’s Name ', '4', '230', '30', 'fatherName', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointfaxNumber', 'jointFax No.', '4', '230', '30', 'faxNumber', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointfullName', 'jointFullname', '1', '230', '-15', '1', 'fullName', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointgender', 'jointGender', '1', '230', '174', '1', 'gender', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointhomeTelNumber', 'jointHome Tel No.', '1', '230', '-31', '1', 'homeTelNumber', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointinvestmentObjectives', 'jointInvestentObjectives', '4', '230', '30', 'investmentObjectives', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointinvestmentObjectiveSpecify', 'jointInvestmentObjectiveSpecify', '4', '230', '30', 'investmentObjectiveSpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointmobNumber', 'jointMobile No.', '1', '230', '-47', '1', 'mobNumber', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointmotherMaidenName', 'jointMother’s Maiden Name ', '4', '230', '30', 'motherMaidenName', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnameOfOtherFinancialInstitution', 'jointNameOfOtherFinancialInstitution', '4', '230', '30', 'nameOfOtherFinancialInstitution', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnameOfPrimarySchool', 'jointName of Primary School Attended', '4', '230', '30', 'nameOfPrimarySchool', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnationality', 'jointNationality', '1', '230', '-63', '1', 'nationality', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnationalitySpecify', 'jointNationality Other Specify', '1', '230', '-78', '1', 'nationalitySpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnetworth', 'jointNetworth', '4', '230', '30', 'networth', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointnricPassport', 'jointNRIC/Passport No.', '1', '230', '-94', '1', 'nric, passport', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointoccupation', 'jointOccupation', '4', '230', '30', 'occupation', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointofficeTelNumber', 'jointOffice Tel No.', '4', '230', '30', 'officeTelNumber', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointpermanentResidentOfSingapore', 'jointPermanent Resident of Singapore', '1', '230', '-189', '1', 'permanentResidentOfSingapore', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressCity, physicalAddressStat', 'jointCity / State', '1', '230', '-204', '1', 'physicalAddressCity, physicalAddressState', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressCountry', 'jointCountry', '1', '230', '-157', '1', 'physicalAddressCountry', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointPhysicalAddressStreet1', 'jointResidential Address', '1', '230', '-141', '1', 'physicalAddressStreet1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressStreet2', 'jointResidential Address', '1', '230', '-173', '1', 'physicalAddressStreet2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressStreet3', 'jointResidential Address', '1', '230', '-126', '1', 'physicalAddressStreet3', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressStreet4', 'jointResidential Address', '1', '230', '142', '1', 'physicalAddressStreet4', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointphysicalAddressZipCode', 'jointPostal Code', '1', '230', '-110', '1', 'physicalAddressZipCode', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointpreviousInvestingExperience ', 'jointPreviousInvestingExperience ', '4', '230', '30', 'previousInvestingExperience ', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointpreviousInvestingExperienceSpecify', 'jointPreviousInvestingExperienceSpecify', '4', '230', '30', 'previousInvestingExperienceSpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointqualifications', 'jointEducational Qualifications', '4', '230', '30', 'qualifications', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointqualificationsSpecify', 'jointEducational Qualifications Other Specify', '4', '230', '30', 'qualificationsSpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointrelatedToAnyEmplfUOB', 'jointRelated to any employee', '4', '230', '30', 'relatedToAnyEmplfUOB', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointrelatedToAnyEmplName1', 'jointName1', '4', '230', '30', 'relatedToAnyEmplName1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointrelatedToAnyEmplName2', 'jointName2', '4', '230', '30', 'relatedToAnyEmplName2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointrelatedToAnyEmplRelation1', 'jointRelationship1', '4', '230', '30', 'relatedToAnyEmplRelation1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointrelatedToAnyEmplRelation2', 'jointRelationship2', '4', '230', '30', 'relatedToAnyEmplRelation2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointsourceOfFundsWealth', 'jointSource of Funds / Wealth', '4', '230', '30', 'sourceOfFundsWealth', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointsourceOfFundsWealthSpecify', 'jointSource of Funds / Wealth Other Specify', '4', '230', '30', 'sourceOfFundsWealthSpecify', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointssn', 'jointUS Taxpayer Identification No.', '1', '230', '16', '1', 'ssn', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointtitle', 'jointTitile', '1', '230', '48', '1', 'title', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointuobAcctHolderControlOverTradeAcct', 'jointany account holder', '4', '230', '30', 'uobAcctHolderControlOverTradeAcct', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointuobAcctHolderControlOverTradeAcctName1', 'jointAccount Name1', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctName1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointuobAcctHolderControlOverTradeAcctName2', 'jointAccount Name2', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctName2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointuobAcctHolderControlOverTradeAcctNumber1', 'jointAccount No.1', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctNumber1', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'jointuobAcctHolderControlOverTradeAcctNumber2', 'jointAccount No.2', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctNumber2', 'Joint', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'mailingAddressStreet4', 'Residential Address', '1', '230', '39', '1', 'mailingAddressStreet4', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'nameOfOtherFinancialInstitution', 'nameOfOtherFinancialInstitution', '4', '230', '30', 'nameOfOtherFinancialInstitution', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'physicalAddressStreet4', 'Residential Address', '1', '230', '55', '1', 'physicalAddressStreet4', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'previousInvestingExperience ', 'previousInvestingExperience ', '4', '230', '30', 'previousInvestingExperience ', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'previousInvestingExperienceSpecify', 'previousInvestingExperienceSpecify', '4', '230', '30', 'previousInvestingExperienceSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'relatedToAnyEmplfUOB', 'related to any employee', '4', '230', '30', 'relatedToAnyEmplfUOB', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'ROBOReferenceNo', 'ROBOReferenceNo.', '4', '230', '30', '', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'sourceOfFundsWealthSpecify', 'Source of Funds / Wealth Other Specify', '4', '230', '30', 'sourceOfFundsWealthSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'trCode', 'TR Code ', '4', '230', '30', '', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'trName', 'TR Name', '4', '230', '30', '', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'uobAcctHolderControlOverTradeAcct', 'any account holder', '4', '230', '30', 'uobAcctHolderControlOverTradeAcct', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'uobAcctHolderControlOverTradeAcctName1', 'Account Name1', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctName1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'uobAcctHolderControlOverTradeAcctName2', 'Account Name2', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctName2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'uobAcctHolderControlOverTradeAcctNumber1', 'Account No.1', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctNumber1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'uobAcctHolderControlOverTradeAcctNumber2', 'Account No.2', '4', '230', '30', 'uobAcctHolderControlOverTradeAcctNumber2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('2', 'UOBKHTradingAccountNo', 'UOBKHTradingAccountNo.', '4', '230', '30', '', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'acctnum', 'acctnum', '1', '230', '650', '5', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'acctnum1', 'acctnum', '1', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'acctnum2', 'acctnum', '2', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'acctTypeId', 'Account Type', '1', '230', '609', '2', 'acctTypeVal', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAccountHolderName', 'Name of Bank Account Holder', '1', '230', '360', '4', 'bankAccountHolderName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAccountNo', 'bankAccountNo', '1', '230', '318', '1', 'bankAccountNo', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressCity,  bankAddressState', 'bankAddressCity,  bankAddressState', '1', '230', '260', '1', 'bankAddressCity', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressCountry', 'bankAddressCountry', '1', '230', '231', '1', 'bankAddressCountry', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressStreet1', 'bankAddressStreet1', '1', '230', '304', '1', 'bankAddressStreet1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressStreet2', 'bankAddressStreet2', '1', '230', '289', '1', 'bankAddressStreet2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressStreet3', 'bankAddressStreet3', '1', '230', '275', '1', 'bankAddressStreet3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankAddressZipCode', 'bankAddressZipCode', '1', '230', '246', '1', 'bankAddressZipCode', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'bankName', 'bankName', '1', '230', '333', '2', 'bankName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'correspondentBank', 'correspondentBank', '1', '230', '202', '1', 'correspondentBank', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'correspondentBankSwiftBic', 'correspondentBankSwiftBic', '1', '230', '187', '1', 'correspondentBankSwiftBic', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'dateOfApplication', 'Date Of Application', '1', '230', '565', '1', 'dateOfApplication', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'emailAddress', 'Email Address', '1', '230', '414', '4', 'emailAddress', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'existingTradeAcctNumber', 'UOBKH Existing Account Number', '1', '230', '635', '1', 'existingTradeAcctNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'fatherName', 'Father’s Name', '2', '230', '416', '1', 'fatherName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'fullName', 'fullname', '1', '230', '496', '5', 'fullName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'icno', 'I C No.', '1', '230', '482', '0', 'icno', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidence1', 'jurisdictionOfTaxResidence1', '2', '110', '606', '13', 'jurisdictionOfTaxResidence1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidence2', 'jurisdictionOfTaxResidence2', '2', '110', '591', '1', 'jurisdictionOfTaxResidence2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidence3', 'jurisdictionOfTaxResidence3', '2', '110', '577', '1', 'jurisdictionOfTaxResidence3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidenceB1', 'jurisdictionOfTaxResidenceB1', '2', '110', '523', '4', 'jurisdictionOfTaxResidenceB1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidenceB2', 'jurisdictionOfTaxResidenceB2', '2', '110', '509', '1', 'jurisdictionOfTaxResidenceB2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'jurisdictionOfTaxResidenceB3', 'jurisdictionOfTaxResidenceB3', '2', '110', '494', '1', 'jurisdictionOfTaxResidenceB3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'mobNumber', 'Mobile No.', '1', '270', '467', '0', 'mobNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'mobNumberCD', 'Mob Number CD', '1', '230', '467', '1', 'mobNumberCD', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'motherMaidenName', 'Mother’s Maiden Name', '2', '230', '431', '5', 'motherMaidenName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'nameOfPrimarySchool', 'Name of Primary School Attended', '2', '230', '401', '1', 'nameOfPrimarySchool', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'nric', 'NRIC', '1', '230', '482', '1', 'nric', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'passport', 'Passport No.', '1', '230', '482', '0', 'passport', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'repId', 'TR Code', '1', '230', '594', '1', 'repId', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'salesPersonName', 'TR Name', '1', '230', '579', '1', 'salesPersonName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'swiftBic', 'swiftBic', '1', '230', '216', '1', 'swiftBic', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'taxIdentificationNumber1', 'taxIdentificationNumber1', '2', '260', '606', '0', 'taxIdentificationNumber1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'taxIdentificationNumber2', 'taxIdentificationNumber2', '2', '260', '591', '0', 'taxIdentificationNumber2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'taxIdentificationNumber3', 'taxIdentificationNumber3', '2', '260', '577', '0', 'taxIdentificationNumber3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableReason1', 'tinUnavailableReason1', '2', '415', '606', '0', 'tinUnavailableReason1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableReason2', 'tinUnavailableReason2', '2', '415', '591', '0', 'tinUnavailableReason2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableReason3', 'tinUnavailableReason3', '2', '415', '577', '0', 'tinUnavailableReason3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableValueB1', 'tinUnavailableValueB1', '2', '260', '523', '0', 'tinUnavailableValueB1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableValueB2', 'tinUnavailableValueB2', '2', '260', '509', '0', 'tinUnavailableValueB2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_EXISTING_USER', 'tinUnavailableValueB3', 'tinUnavailableValueB3', '2', '260', '494', '0', 'tinUnavailableValueB3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctnum', 'acctnum', '1', '230', '650', '5', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctnum1', 'acctnum', '1', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctnum2', 'acctnum', '2', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctnum3', 'acctnum', '3', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctnum4', 'acctnum', '4', '490', '723', '1', 'acctnum', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'acctTypeId', 'Account Type', '1', '230', '635', '1', 'acctTypeVal', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'annualIncome', 'Annual Income', '3', '230', '353', '4', 'annualIncome', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'areYouUnableToPayYouDebts', 'areYouUnableToPayYouDebts', '4', '230', '455', '9', 'areYouUnableToPayYouDebts', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'areYouUnableToPayYouDebtsDescribe', 'areYouUnableToPayYouDebtsDescribe', '4', '80', '428', '2', 'areYouUnableToPayYouDebtsDescribe', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAccountHolderName', 'Name of Bank Account Holder', '2', '230', '481', '4', 'bankAccountHolderName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAccountNo', 'bankAccountNo', '2', '230', '439', '1', 'bankAccountNo', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressCity,  bankAddressState', 'bankAddressCity,  bankAddressState', '2', '230', '381', '1', 'bankAddressCity', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressCountry', 'bankAddressCountry', '2', '230', '352', '1', 'bankAddressCountry', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressStreet1', 'bankAddressStreet1', '2', '230', '425', '1', 'bankAddressStreet1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressStreet2', 'bankAddressStreet2', '2', '230', '410', '1', 'bankAddressStreet2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressStreet3', 'bankAddressStreet3', '2', '230', '396', '1', 'bankAddressStreet3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankAddressZipCode', 'bankAddressZipCode', '2', '230', '367', '1', 'bankAddressZipCode', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'bankName', 'bankName', '2', '230', '454', '2', 'bankName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'consentCallContact', 'consentCallContact', '4', '230', '231', '8', 'consentCallContact', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'consentTextContact', 'consentTextContact', '4', '230', '217', '1', 'consentTextContact', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'correspondentBank', 'correspondentBank', '2', '230', '323', '1', 'correspondentBank', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'correspondentBankSwiftBic', 'correspondentBankSwiftBic', '2', '230', '309', '1', 'correspondentBankSwiftBic', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'countryOfBirth', 'Country of Birth', '1', '230', '466', '1', 'countryOfBirth', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'countryOfBirthSpecify', 'Country of Birth Other Specify', '1', '320', '466', '0', 'countryOfBirthSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'dateOfApplication', 'Date Of Application', '1', '230', '592', '1', 'dateOfApplication', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'dob', 'Date of Birth (DD/MM/YYYY)', '1', '230', '452', '1', 'dobDDMMYYYY', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'doYouHaveAnyDisputedAccount', 'doYouHaveAnyDisputedAccount', '4', '230', '372', '4', 'doYouHaveAnyDisputedAccount', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'doYouHaveAnyDisputedAccountDescribe', 'doYouHaveAnyDisputedAccountDescribe', '4', '80', '345', '2', 'doYouHaveAnyDisputedAccountDescribe', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'emailAddress', 'Email Address', '1', '230', '367', '1', 'emailAddress', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerCity,employerState', 'City / State', '3', '230', '451', '1', 'employerCity', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerName', 'Name of Employer', '3', '230', '509', '1', 'employerName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerStreetAddress1', 'Employer Address', '3', '230', '494', '1', 'employerStreetAddress1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerStreetAddress2', 'Employer Address', '3', '230', '480', '1', 'employerStreetAddress2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerStreetAddress3', 'Employer Address', '3', '230', '465', '1', 'employerStreetAddress3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerZipCode', 'Postal Code', '3', '230', '436', '1', 'employerZipCode', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employerZipCountry', 'Country', '3', '230', '422', '1', 'employerZipCountry', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'employmentStatus', 'Employment Status', '3', '230', '553', '5', 'emplTypeId', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'fatherName', 'Father’s Name', '3', '230', '635', '1', 'fatherName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'fullName', 'fullname', '1', '230', '510', '1', 'fullName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'gender', 'gender', '1', '230', '495', '1', 'gender', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'goodsServicesTax', 'Goods & Services Tax', '3', '230', '268', '3', 'havingGST', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'homeTelNumber', 'Home Tel No.', '1', '270', '381', '0', 'homeTelNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'homeTelNumberCD', 'Home TelNumber CD', '1', '230', '381', '1', 'homeTelNumberCD', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'icno', 'I C No.', '1', '230', '481', '0', 'icno', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidence1', 'jurisdictionOfTaxResidence1', '2', '110', '198', '8', 'jurisdictionOfTaxResidence1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidence2', 'jurisdictionOfTaxResidence2', '2', '110', '183', '1', 'jurisdictionOfTaxResidence2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidence3', 'jurisdictionOfTaxResidence3', '2', '110', '169', '1', 'jurisdictionOfTaxResidence3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidenceB1', 'jurisdictionOfTaxResidenceB1', '2', '110', '113', '4', 'jurisdictionOfTaxResidenceB1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidenceB2', 'jurisdictionOfTaxResidenceB2', '2', '110', '98', '1', 'jurisdictionOfTaxResidenceB2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'jurisdictionOfTaxResidenceB3', 'jurisdictionOfTaxResidenceB3', '2', '110', '84', '1', 'jurisdictionOfTaxResidenceB3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailAddressSameAsPhysical', 'Mailing Address Same As Physical', '2', '230', '650', '5', 'mailAddressSameAsPhysical', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressCity, mailingAddressState', 'Mailing City / State', '2', '230', '564', '1', 'mailingAddressCity', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressCountry', 'Mailing Country', '2', '230', '535', '1', 'mailingAddressCountry', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressStreet1', 'Mailing Address', '2', '230', '608', '1', 'mailingAddressStreet1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressStreet2', 'Mailing Address', '2', '230', '593', '1', 'mailingAddressStreet2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressStreet3', 'Mailing Address', '2', '230', '578', '1', 'mailingAddressStreet3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mailingAddressZipCode', 'Mailing Postal Code', '2', '230', '549', '1', 'mailingAddressZipCode', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mobNumber', 'Mobile No.', '1', '270', '396', '0', 'mobNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'mobNumberCD', 'Mob Number CD', '1', '230', '396', '2', 'mobNumberCD', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'motherMaidenName', 'Mother’s Maiden Name', '3', '230', '650', '5', 'motherMaidenName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'nameOfPrimarySchool', 'Name of Primary School Attended', '3', '230', '621', '1', 'nameOfPrimarySchool', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'nationality', 'Nationality', '1', '230', '437', '1', 'nationality', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'nationalitySpecify', 'Nationality Other Specify', '1', '320', '437', '0', 'nationalitySpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'networth', 'Networth', '3', '230', '324', '1', 'networth', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'nric', 'NRIC', '1', '230', '481', '1', 'nric', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'occupation', 'Occupation', '3', '230', '523', '1', 'occupation', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'officeTelNumber', 'Office Tel No.', '3', '270', '407', '0', 'officeTelNumber', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'officeTelNumberCD', 'Office Tel Number CD', '3', '230', '407', '1', 'officeTelNumberCD', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'passport', 'Passport No.', '1', '230', '481', '0', 'passport', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'permanentRsdntOfSingapore', 'Permanent Resident of Singapore', '1', '230', '423', '1', 'permanentRsdntOfSingapore', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressCity, physicalAddressState', 'Residential City / State', '1', '230', '269', '1', 'physicalAddressCity', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressCountry', 'Residential Country', '1', '230', '240', '1', 'physicalAddressCountry', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressStreet1', 'Residential Address', '1', '230', '313', '4', 'physicalAddressStreet1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressStreet2', 'Residential Address', '1', '230', '298', '1', 'physicalAddressStreet2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressStreet3', 'Residential Address', '1', '230', '284', '1', 'physicalAddressStreet3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'physicalAddressZipCode', 'Residential Postal Code', '1', '230', '255', '1', 'physicalAddressZipCode', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'qualifications', 'Educational Qualifications', '3', '230', '310', '1', 'qualifications', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'qualificationsSpecify', 'Educational Qualifications Other Specify', '3', '350', '310', '0', 'qualificationsSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'reasonForMailAddreDiffer', 'reasonForMailAddreDiffer', '2', '230', '622', '2', 'reasonForMailAddreDiffer', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'relatedToAnyEmplfUOB', 'relatedToAnyEmplfUOB', '4', '505', '645', '1', 'relatedToAnyEmplfUOB', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'relatedToAnyEmplName1', 'Name1', '4', '230', '630', '1', 'relatedToAnyEmplName1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'relatedToAnyEmplName2', 'Name2', '4', '230', '601', '1', 'relatedToAnyEmplName2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'relatedToAnyEmplRelation1', 'Relationship1', '4', '230', '616', '1', 'relatedToAnyEmplRelation1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'relatedToAnyEmplRelation2', 'Relationship2', '4', '230', '587', '1', 'relatedToAnyEmplRelation2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'repId', 'TR Code', '1', '230', '621', '1', 'repId', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'salesPersonName', 'TR Name', '1', '230', '606', '1', 'salesPersonName', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'sourceOfFundsWealth', 'Source of Funds / Wealth', '3', '230', '339', '1', 'sourceOfFundsWealth', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'sourceOfFundsWealthSpecify', 'Source of Funds / Wealth Other Specify', '3', '350', '339', '0', 'sourceOfFundsWealthSpecify', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'swiftBic', 'swiftBic', '2', '230', '338', '1', 'swiftBic', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'taxIdentificationNumber1', 'taxIdentificationNumber1', '2', '260', '198', '0', 'taxIdentificationNumber1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'taxIdentificationNumber2', 'taxIdentificationNumber2', '2', '260', '183', '0', 'taxIdentificationNumber2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'taxIdentificationNumber3', 'taxIdentificationNumber3', '2', '260', '169', '0', 'taxIdentificationNumber3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableReason1', 'tinUnavailableReason1', '2', '415', '198', '0', 'tinUnavailableReason1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableReason2', 'tinUnavailableReason2', '2', '415', '183', '0', 'tinUnavailableReason2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableReason3', 'tinUnavailableReason3', '2', '415', '169', '0', 'tinUnavailableReason3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableValueB1', 'tinUnavailableValueB1', '2', '260', '113', '0', 'tinUnavailableValueB1', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableValueB2', 'tinUnavailableValueB2', '2', '260', '98', '0', 'tinUnavailableValueB2', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'tinUnavailableValueB3', 'tinUnavailableValueB3', '2', '260', '84', '0', 'tinUnavailableValueB3', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'title', 'titile', '1', '230', '524', '5', 'title', 'Client', 'N', 'N');
INSERT INTO `service`.`pdf_file_rules` (`fileId`, `dataField`, `description`, `pageNo`, `xcord`, `ycord`, `length`, `dbColumn`, `role`, `isRequired`, `needToEncrypt`) VALUES ('UOB_ACCT_OPEN_NEW_USER', 'unemploymentReason', 'Unemployment Reason', '3', '230', '538', '1', 'reasonForUnemployment', 'Client', 'N', 'N');
