UPDATE `invdb`.`web_site_info` SET `value`='8.UOB' WHERE `url`='uwealth' and`name`='DEFAULT.MODEL';
UPDATE `invdb`.`web_site_info` SET `value`='UOB' WHERE `url`='uwealth' and`name`='DEFAULT.ADVISOR';
UPDATE `invdb`.`web_site_info` SET `value`='5000' WHERE `url`='uwealth' and`name`='INVESTMENT.MIN1ST';
UPDATE `invdb`.`web_site_info` SET `value`='5000' WHERE `url`='uwealth' and`name`='INVESTMENT.MIN2ND';
UPDATE `invdb`.`web_site_info` SET `value`='500' WHERE `url`='uwealth' and`name`='INVESTMENT.RECURRING1ST';
UPDATE `invdb`.`web_site_info` SET `value`='500' WHERE `url`='uwealth' and`name`='INVESTMENT.RECURRING2ND';


INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('601', 'A', 'A', '1306.T', 'NULL', 'NULL', '1306.T', 'TOPIX EXCHANGE TRADED', 'Equity', 'Japan Equities', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'TSE', 'JPY');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('611', 'A', 'A', 'IEMB.L', 'NULL', 'NULL', 'IEMB.L', 'iShares J P Morgan $EM Bond ETF', 'Fixed Income', 'Emerging Market Bonds', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'LSE', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('612', 'A', 'A', 'IEML.L', 'NULL', 'NULL', 'IEML.L', 'iShares J P Morgan $EM Local Bond ETF', 'Fixed Income', 'Emerging Market Local Bonds', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'LSE', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('610', 'A', 'A', 'LQDE.L', 'NULL', 'NULL', 'LQDE.L', 'iShares $ Corp Bond UCITS ETF USD (Dist)', 'Fixed Income', 'Corporate Bonds', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'LSE', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('603', 'A', 'A', 'VAS.AX', 'NULL', 'NULL', 'VAS.AX', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'ASX', 'AUD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('600', 'A', 'A', 'VEUR.L', 'NULL', 'NULL', 'VEUR.L', 'VANGUARD FTSE DEV EU UCITS ETF', 'Equity', 'Europe Equities', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'LSE', 'GBP');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('602', 'A', 'A', 'XIC.TO', 'NULL', 'NULL', 'XIC.TO', 'iShares Core SP TSX CA', 'Equity', 'Australian Equities', 'NULL', 'NULL', '0', 'NULL', 'NULL', '0', 'NULL', 'TSE', 'CAD');
