delete from invdb.notification_message_lookup where advisor='UOB';

INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'ACTIVE', 'Y', 'Account Activated and Funded', 'Y', 'Account Activated and Funded', 'operations@uobkh.com', 'Y', 'Account Activated and Funded', '2017-07-27 07:22:24');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'CHNGADDRS', 'Y', 'Change Address', 'Y', 'Change Address', 'operations@uobkh.com', 'N', 'Change Address', '2017-07-27 07:22:24');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'FUNDED', 'Y', 'Funded Account', 'Y', 'Funded Account', 'operations@uobkh.com', 'Y', 'Funded Account', '2017-07-27 07:22:24');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'OPENED', 'Y', 'Application is Opened', 'Y', 'Application is Opened', 'operations@uobkh.com', 'Y', 'Application is Opened', '2017-07-27 07:22:24');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'PRFLCNFIRMED', 'Y', 'Portfolio Confirmed', 'N', 'Portfolio Confirmed', 'operations@uobkh.com', 'Y', 'Portfolio Confirmed', '2018-01-08 06:44:58');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'PRFLCNFREQ', 'Y', 'Portfolio Confirmation Request', 'N', 'Portfolio Confirmation Request', 'operations@uobkh.com', 'Y', 'Portfolio Confirmation Request', '2018-01-08 06:44:21');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'PROCESSED', 'Y', 'Application Submitted', 'Y', 'Application Submitted', 'operations@uobkh.com', 'Y', 'Application Submitted', '2017-07-27 07:22:24');
INSERT INTO `invdb`.`notification_message_lookup` (`advisor`, `messageType`, `includeAdvisor`, `advisorsubject`, `includeAdvisorEmail`, `emailAdvisorSubject`, `emailAdvisorRecepient`, `includeUser`, `userSubject`, `created`) VALUES ('UOB', 'REBALANCE', 'Y', 'Changed Strategy', 'Y', 'Changed Strategy', 'operations@uobkh.com', 'N', 'Changed Strategy', '2017-07-27 07:22:24');
