use invdb;
drop table if exists `user_trade_profile_audit`;
CREATE TABLE `user_trade_profile_audit` (
 `prfid` bigint(20) NOT NULL AUTO_INCREMENT,
  `acctnum` bigint(20) NOT NULL ,
  `advisor` varchar(20) DEFAULT NULL,
  `rep` varchar(20) DEFAULT NULL,
  `theme` varchar(30) DEFAULT NULL,
  `firstname` varchar(40) DEFAULT NULL,
  `lastname` varchar(40) DEFAULT NULL,
  `portfolioName` varchar(60) DEFAULT NULL,
  `goal` varchar(30) DEFAULT NULL,
  `acctType` varchar(30) DEFAULT NULL,
  `age` int(5) DEFAULT NULL,
  `horizon` int(5) DEFAULT NULL,
  `initialInvestment` int(11) DEFAULT NULL,
  `recurringInvestment` int(11) DEFAULT NULL,
  `experience` tinyint(4) DEFAULT NULL,
  `longTermGoal` tinyint(4) DEFAULT NULL,
  `stayInvested` tinyint(4) DEFAULT NULL,
  `charitablegoals` int(11) DEFAULT NULL,
  `dependent` int(11) DEFAULT NULL,
  `riskIndex` double DEFAULT NULL,
  `tradePreference` varchar(1) DEFAULT 'A',
  `keepLiquid` int(11) DEFAULT NULL,
  `taxable` varchar(1) DEFAULT NULL,
  `calcModel` varchar(1) DEFAULT NULL,
  `assetIndex` int(3) DEFAULT NULL,
  `portfolioIndex` int(3) DEFAULT NULL,
  `goalAmount` double DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `ip` varchar(20) DEFAULT NULL,
  `created` date DEFAULT NULL,
  `lastUpdated` date DEFAULT NULL,
  `managed` varchar(1) NOT NULL DEFAULT 'N',
  `clientAccountID` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`prfid`)
) ENGINE=InnoDB AUTO_INCREMENT=2348 DEFAULT CHARSET=utf8;
