DROP TABLE `user_trade_profile`;

CREATE TABLE `user_trade_profile` (
  `acctnum` bigint(20) NOT NULL AUTO_INCREMENT,
  `profileName` varchar(30),
  `age` integer,
  `horizon` integer,
  `initialInvestment` integer,
  `recurringInvestment` integer,
  `experience` tinyint,
  `objective` tinyint,
  `investmentplan` tinyint,
  `charitablegoals` integer,
  `dependent` integer,
  `minorName` varchar(60),
  `minorage` integer,
  `mortgage` integer,
  `medical`  integer,
  `autoloans` integer,
  `lifeInsurance` integer,
  `autoInsurance` integer,
  `creditCardDebt` integer,
  `otherdebts` double,
  `currentincome` integer,
  `taxrate` double,
  `annuities` integer,
  `investmentProperties` integer,
  `moneymarket` integer,
  `mutualfund` integer,
  `insuranceeCashValue` integer,
  `insuranceCoverage` integer,
  `otherSavings` integer,
  `riskIndex` double,
  `created` date,
  `lastUpdated` date, 
  PRIMARY KEY (`acctnum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
