UPDATE `invdb`.`web_site_info` SET `value`='css/bellrock.css' WHERE `url`='200deep' and`name`='CSS.CUSTODY';
UPDATE `invdb`.`web_site_info` SET `value`='css/bellrock.css' WHERE `url`='200deep' and`name`='CSS.CUSTOM';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock' WHERE `url`='200deep' and`name`='CSS.DIR';
UPDATE `invdb`.`web_site_info` SET `value`='/data/upload/bellock/consumerUpload/' WHERE `url`='200deep' and`name`='CUSTODY.UPLOAD.PATH';
UPDATE `invdb`.`web_site_info` SET `value`='BELLROCK' WHERE `url`='200deep' and`name`='DEFAULT.ADVISOR';
UPDATE `invdb`.`web_site_info` SET `value`='USD' WHERE `url`='200deep' and`name`='DEFAULT.CURRENCY';
UPDATE `invdb`.`web_site_info` SET `value`='BELLROCK.T1' WHERE `url`='200deep' and`name`='DEFAULT.MODEL';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock' WHERE `url`='200deep' and`name`='DIR.CONSUMER';
UPDATE `invdb`.`web_site_info` SET `value`='Welcome to 200Deep - Activate Your Account' WHERE `url`='200deep' and`name`='EMAIL.ACTIVATE.SUBJECT';
UPDATE `invdb`.`web_site_info` SET `value`='200Deep - Reset Your Password' WHERE `url`='200deep' and`name`='EMAIL.FORGOT.SUBJECT';
UPDATE `invdb`.`web_site_info` SET `value`='200Deep - Account is locked' WHERE `url`='200deep' and`name`='EMAIL.LOCKED.SUBJECT';
UPDATE `invdb`.`web_site_info` SET `value`='info@200deep.com' WHERE `url`='200deep' and`name`='EMAIL.MAIN';
UPDATE `invdb`.`web_site_info` SET `value`='operations@200deep.com' WHERE `url`='200deep' and`name`='EMAIL.OPERATION';
UPDATE `invdb`.`web_site_info` SET `value`='200Deep - Reset Your Password' WHERE `url`='200deep' and`name`='EMAIL.RESET.SUBJECT';
UPDATE `invdb`.`web_site_info` SET `value`='support@200deep.com' WHERE `url`='200deep' and`name`='EMAIL.SUPPORT';
UPDATE `invdb`.`web_site_info` SET `value`='noreply@200deep.com' WHERE `url`='200deep' and`name`='EMAIL.USER';
UPDATE `invdb`.`web_site_info` SET `value`='Welcome to 200Deep - Activate Your Account' WHERE `url`='200deep' and`name`='EMAIL.WELCOME.SUBJECT';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock-Activated.html' WHERE `url`='200deep' and`name`='HTML.ACTIVATED';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock-Forgot.html' WHERE `url`='200deep' and`name`='HTML.FORGOT';
UPDATE `invdb`.`web_site_info` SET `value`='bel-Locked.html' WHERE `url`='200deep' and`name`='HTML.LOCKED';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock-Reset.html' WHERE `url`='200deep' and`name`='HTML.RESET';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock-Welcome.html' WHERE `url`='200deep' and`name`='HTML.WELCOME';
UPDATE `invdb`.`web_site_info` SET `value`='bellrock-Welcome.html' WHERE `url`='200deep' and`name`='HTML.WELCOME.ADV';
UPDATE `invdb`.`web_site_info` SET `value`='PROD' WHERE `url`='200deep' and`name`='SERVICE.DOCUMENT.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='https://200deep.comt/mobilelogin.xhtml' WHERE `url`='200deep' and`name`='URL.MOBILE';
UPDATE `invdb`.`web_site_info` SET `value`='https://200deep.com' WHERE `url`='200deep' and`name`='URL.SECURE';
UPDATE `invdb`.`web_site_info` SET `value`='http://200deep.com' WHERE `url`='200deep' and`name`='URL.WEBSITE';
UPDATE `invdb`.`web_site_info` SET `value`='200 Deep' WHERE `url`='200deep' and`name`='WEB.COMPANYNAME';
UPDATE `invdb`.`web_site_info` SET `value`='Bell Rock' WHERE `url`='200deep' and`name`='WEB.COPYRIGHT';
UPDATE `invdb`.`web_site_info` SET `value`='' WHERE `url`='200deep' and`name`='WEB.GOOGLEANALYTICS';
UPDATE `invdb`.`web_site_info` SET `value`='' WHERE `url`='200deep' and`name`='WEB.SSLSEAL';


-- ----------------------------
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.AGGREGATION.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.CRM.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.DOCUMENT.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.DOCUSIGN.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.EMAILER.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.PRICING.MODE';
UPDATE `invdb`.`web_site_info` SET `value`='images/logo/200DeepLogo.png' WHERE `url`='200deep' and`name`='WEB.LOGO';
UPDATE `invdb`.`web_site_info` SET `value`='XXX XXX-XXXX' WHERE `url`='200deep' and`name`='PHONE.MAIN';
UPDATE `invdb`.`web_site_info` SET `value`='XXX XXX-XXXX' WHERE `url`='200deep' and`name`='PHONE.SUPPORT';
UPDATE `invdb`.`web_site_info` SET `value`='/javax.faces.resource/images/200DeepLogo.png.xhtml?ln=tcm' WHERE `url`='200deep' and`name`='WEB.FAVICONLOGO';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='SERVICE.CUSTODY';
UPDATE `invdb`.`web_site_info` SET `value`='1000' WHERE `url`='200deep' and`name`='INVESTMENT.MIN1ST';
UPDATE `invdb`.`web_site_info` SET `value`='UAT' WHERE `url`='200deep' and`name`='WEB.MODE';
