

INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRD', '7', 'Y', 'tmp_td_demographic', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'Y', 'DB', 'sp_upload_td_demographic', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'SEC', '8', 'Y', 'tmp_td_security', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'DB', 'sp_upload_td_sec_master', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'PRI', '9', 'Y', 'tmp_td_price', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'DB', '', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'POS', '10', 'Y', 'tmp_td_position', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'N', 'DB', '', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRN', '11', 'Y', 'tmp_td_transaction', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'N', 'N', 'DB', '', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'CBL', '12', 'Y', 'tmp_td_unrealized', 'DAILY', '/data/download/tcm/ALRG', '/data/eodfiles/tcm/ALRG', 'csv', 'Y', 'N', 'DB', 'sp_upload_td_unrealized', '2017-04-24 04:51:38', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRD', '13', 'Y', 'tmp_td_demographic', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'Y', 'DB', 'sp_upload_td_demographic', '2017-04-25 05:14:41', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'SEC', '14', 'Y', 'tmp_td_security', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'DB', 'sp_upload_td_sec_master', '2017-04-25 05:14:41', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'PRI', '15', 'Y', 'tmp_td_price', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'DB', '', '2017-04-25 05:14:41', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'POS', '16', 'Y', 'tmp_td_position', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'DB', '', '2017-04-25 05:14:41', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'TRN', '17', 'Y', 'tmp_td_transaction', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'DB', '', '2017-04-25 05:14:41', 'N', '1', 'csv');
INSERT INTO invdb.download_files (vendor, filename, seqno, active, tmp_tableName, available, sourcepath, downloaddir, loadFormat, required, canbeempty, postProcess, postInstruction, created, containsheader, keyData, fileExtension) VALUES ('TD', 'CBL', '18', 'Y', 'tmp_td_unrealized', 'DAILY', '/data/download/tcm/DAFF', '/data/eodfiles/tcm/DAFF', 'csv', 'N', 'N', 'DB', 'sp_upload_td_unrealized', '2017-04-25 05:14:41', 'N', '1', 'csv');


UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='CBL' and seqno='6';
UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='POS' and seqno='4';
UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='PRI' and seqno='3';
UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='SEC' and seqno='2';
UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='TRD' and seqno='1';
UPDATE invdb.download_files SET sourcepath='/data/download/tcm/AGWQ', downloaddir='/data/eodfiles/tcm/AGWQ' WHERE vendor='TD' and filename='TRN' and seqno='5';
