create table sec_master_20170524
as select * from sec_master;

DROP TABLE `sec_master`;
 
CREATE TABLE `sec_master` (
  `instrumentid` bigint(20) NOT NULL AUTO_INCREMENT,
  `status` varchar(1) DEFAULT 'A' COMMENT 'A - Active, I - Inactive',
  `securityStatus` varchar(1) DEFAULT 'A' COMMENT 'A-Active,M - Matured,D - Defaulted,S - Split,R - Reverse Split',
  `ticker` varchar(20) NOT NULL,
  `cusip` varchar(12) DEFAULT NULL,
  `isin` varchar(15) DEFAULT NULL,
  `ric` varchar(45) DEFAULT NULL,
  `name` varchar(60) DEFAULT NULL,
  `assetclass` varchar(40) DEFAULT NULL COMMENT 'Equities, Bonds, Commodities, etc.',
  `subclass` varchar(40) DEFAULT NULL COMMENT 'LargeCap, SmallCap, etc.',
  `type` varchar(30) DEFAULT NULL COMMENT 'Equity,Bond,Cash',
  `style` varchar(30) DEFAULT NULL COMMENT 'Value,Growth,Divident',
  `expenseRatio` double DEFAULT NULL,
  `inception` date DEFAULT NULL,
  `issuer` varchar(20) DEFAULT NULL,
  `securityRiskSTD` double DEFAULT NULL,
  `rbsaFlag` varchar(1) DEFAULT NULL,
  `exchange` varchar(10) DEFAULT 'NYSE',
  `base_currency` varchar(3) DEFAULT 'USD',
  PRIMARY KEY (`instrumentid`),
  INDEX `AK1_sec_master` (`ticker`), 
  INDEX `AK2_sec_master` (`cusip`),
  INDEX `AK3_sec_master` (`isin`),
  INDEX `AK4_sec_master` (`ric`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('1', 'A', 'A', 'Cash', null, null, 'Cash', 'Cash', 'Cash', 'Cash', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('2', 'A', 'A', 'BIL.N', null, null, 'BIL.N', 'Cash', 'Cash', 'Cash', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('3', 'A', 'A', 'BKLN', null, null, 'BKLN', 'PowerShares Senior Loan', 'Bond', 'Senior Loan', null, null, '0.0065', null, null, '0.022778', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('4', 'A', 'A', 'CWB', null, null, 'CWB', 'SPDR Barclays Capital Convertible Secs', 'Bond', 'Convertible', null, null, '0.004', null, null, '0.098135', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('5', 'A', 'A', 'EEM', null, null, 'EEM', 'iShares MSCI Emerging Markets', 'International', 'Emerging Market', null, null, '0.0067', null, null, '0.162104', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('6', 'A', 'A', 'EFA', null, null, 'EFA', 'iShares MSCI EAFE', 'International', 'Large Cap Int', null, null, '0.0034', null, null, '0.122497', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('7', 'A', 'A', 'EMB', null, null, 'EMB', 'iShares JPMorgan USD Emerg Markets Bond', 'Bond', 'Emerging HY', null, null, '0.0007', null, null, '0.052482', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('8', 'A', 'A', 'EMLC', null, null, 'EMLC', 'Market Vector EM Local Currency', 'HighYield', 'Emerging HY', null, null, '0.0047', null, null, '0.071652', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('9', 'A', 'A', 'FCNTX', null, null, 'FCNTX', 'Fidelity® Contrafund®', 'Mutual Fund', 'Mix', null, null, '0.0063', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('10', 'A', 'A', 'FFKEX', null, null, 'FFKEX', 'Fidelity Freedom 2030', 'Mutual Fund', 'Mix', null, null, '0.0063', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('11', 'A', 'A', 'GLD', null, null, 'GLD', 'SPDR® Gold Shares', 'Commodity', 'Precious Metals', null, null, '0.004', null, null, '0.134075', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('12', 'A', 'A', 'HYG', null, null, 'HYG', 'iShares iBoxx $ High Yield Corporate Bd', 'Bond', 'Corporate Junk', null, null, '0.005', null, null, '0.040909', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('13', 'A', 'A', 'IAU', null, null, 'IAU', 'iShares Gold Trust', 'Alternative', 'Gold', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('14', 'A', 'A', 'IEF', null, null, 'IEF', 'iShares 7-10 Year Treasury Bond', 'Bond', 'Medium Term', null, null, '0.0015', null, null, '0.048191', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('15', 'A', 'A', 'IJR', null, null, 'IJR', 'iShares Core S&P Small-Cap', 'Domestic', 'Small Cap', null, null, '0.0028', null, null, '0.153552', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('16', 'A', 'A', 'ITM', null, null, 'ITM', 'Market Vectors Intermediate Muni', 'Bond', 'Medium Term', null, null, '0.0024', null, null, '0.030404', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('17', 'A', 'A', 'IVV', null, null, 'IVV', 'iShares Core S&P 500', 'Domestic', 'Large Cap', null, null, '0.0007', null, null, '0.10901', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('18', 'A', 'A', 'IVW', null, null, 'IVW', 'iShares S&P 500 Growth', 'Domestic', 'LargeCap Growth', null, null, '0.0018', null, null, '0.118889', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('19', 'A', 'A', 'IWB', null, null, 'IWB', 'iShares Russell 1000', 'Domestic', 'Large Cap', null, null, '0.0015', null, null, '0.110353', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('20', 'A', 'A', 'IWM', null, null, 'IWM', 'iShares Russell 2000', 'Domestic', 'Small Cap', null, null, '0.0028', null, null, '0.153552', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('21', 'A', 'A', 'IWR', null, null, 'IWR', 'iShares Russell Mid-Cap', 'Domestic', 'Mid Cap', null, null, '0.2', null, null, '0.120254', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('22', 'A', 'A', 'IYR', null, null, 'IYR', 'iShares US Real Estate', 'Domestic', 'RealEstateTrust', null, null, '0.0045', null, null, '0.102856', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('23', 'A', 'A', 'JNK', null, null, 'JNK', 'SPDR Barclays High Yield Bond ETF', 'HighYield', 'Corporate Junk', null, null, '0.004', null, null, '0.041494', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('24', 'A', 'A', 'LQD', null, null, 'LQD', 'iShares iBoxx $ Invst Grade Crp Bond (LQD)', 'Bond', 'Investment Grade', null, null, '0.0007', null, null, '0.042155', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('25', 'A', 'A', 'LSHIX', null, null, 'LSHIX', 'Loomis Sayles Instl High Income', 'Mutual Fund', 'Mix', null, null, '0.0068', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('26', 'A', 'A', 'LTPZ', null, null, 'LTPZ', 'BofA ML 15+ Year US Inflation Linked Treasury', 'Bond', 'TIPS', null, null, '0.002', null, null, '0.117131', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('27', 'A', 'A', 'MALOX', null, null, 'MALOX', 'BlackRock Global Allocation', 'Mutual Fund', 'Mix', null, null, '0.0063', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('28', 'A', 'A', 'MDY', null, null, 'MDY', 'SPDR S&P MidCap 400 ETF', 'Domestic', 'Mid Cap', null, null, '0.0025', null, null, '0.128349', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('29', 'A', 'A', 'MLN', null, null, 'MLN', 'Market Vectors Long Municipal', 'Bond', 'Long Term', null, null, '0.0024', null, null, '0.048282', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('30', 'A', 'A', 'MUB', null, null, 'MUB', 'iShares National AMT-Free Muni Bond', 'Bond', 'Medium Term', null, null, '0.0025', null, null, '0.028862', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('31', 'A', 'A', 'OAKIX', null, null, 'OAKIX', 'Oakmark International I', 'Mutual Fund', 'Mix', null, null, '0.0095', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('32', 'A', 'A', 'PFF', null, null, 'PFF', 'iShares US Preferred Stock', 'Domestic', 'Preferred', null, null, '0.0048', null, null, '0.042116', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('33', 'A', 'A', 'SHM', null, null, 'SHM', 'SPDR Nuveen Barclays ST Muni Bd', 'Bond', 'Short Term', null, null, '0.002', null, null, '0.013782', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('34', 'A', 'A', 'SHY', null, null, 'SHY', 'iShares 1-3 Year Treasury Bond', 'Bond', 'Short Term', null, null, '0.0015', null, null, '0.006902', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('35', 'A', 'A', 'SPY', null, null, 'SPY', 'SPDR S&P 500', 'Domestic', 'Large Cap', null, null, '0.0009', null, null, '0.104227', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('36', 'A', 'A', 'STPZ', null, null, 'STPZ', 'BofA ML 1-5 Year US Inflation Linked Treasury', 'Bond', 'TIPS', null, null, '0.002', null, null, '0.018082', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('37', 'A', 'A', 'SUB', null, null, 'SUB', 'iShares ST National AMTFree Muni Bnd', 'Bond', 'Municipal', null, null, '0.0025', null, null, '0.010566', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('38', 'A', 'A', 'TIPZ', null, null, 'TIPZ', 'BofA ML US Inflation Linked Treasury', 'Bond', 'TIPS', null, null, '0.002', null, null, '0.047781', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('39', 'A', 'A', 'TLT', null, null, 'TLT', 'iShares 20+ Year Treasury Bond', 'Bond', 'Long Term', null, null, '0.0015', null, null, '0.104806', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('40', 'A', 'A', 'VCLT', null, null, 'VCLT', 'Vanguard Long Term Corporate', 'HighYield', 'Investment Grade', null, null, '0.0012', null, null, '0.074551', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('42', 'A', 'A', 'VEU', null, null, 'VEU', 'Vanguard FTSE All-World ex-US', 'International', 'Large Cap', null, null, '0.0015', null, null, '0.112023', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('43', 'A', 'A', 'VGK', null, null, 'VGK', 'Vanguard European Stock Index ETF', 'International', 'Large Cap', null, null, '0.0012', null, null, '0.135258', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('44', 'A', 'A', 'VNQ', null, null, 'VNQ', 'Vanguard REIT', 'Alternative', 'RealEstateTrust', null, null, '0.0025', null, null, '0.114353', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('45', 'A', 'A', 'VOO', null, null, 'VOO', 'Vanguard S&P 500 ETF', 'Domestic', 'Large Cap', null, null, '0.0005', null, null, '0.110353', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('47', 'A', 'A', 'VWO', null, null, 'VWO', 'Vanguard FTSE Emerging Markets', 'International', 'Emerging Market', null, null, '0.0015', null, null, '0.15477', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('65', 'A', 'A', 'AGAZX', null, null, 'AGAZX', '361 Global Long/Short Equity Institutional Fund', 'Alternatives', 'Long/Short Equity', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('66', 'A', 'A', 'AVRPX', null, null, 'AVRPX', 'Stone Ridge All Asset Variance Risk Premium Fund', 'Alternatives', 'Variance Risk Premiu', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('67', 'A', 'A', 'EMRIX', null, null, 'EMRIX', 'VanEck Emerging Markets Institutional Fund', 'Emerging Markets Equ', 'Diversified EM', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('68', 'A', 'A', 'LENDX', null, null, 'LENDX', 'Stone Ridge Alternative Lending Risk Premium Fund', 'Fixed Income', 'Alternative Lending', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('69', 'A', 'A', 'LJMIX', null, null, 'LJMIX', 'LJM Preservation and Growth Instl Fund', 'Alternatives', 'Large ', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('70', 'A', 'A', 'SCZ', null, null, 'SCZ', 'iShares MSCI EAFE Small-Cap', 'International Equity', 'Small/Mid Blend', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('71', 'A', 'A', 'SRRIX', null, null, 'SRRIX', 'Stone Ridge Reinsurance Risk Premium Interval Fund', 'Alternatives', 'Reinsurance', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('72', 'A', 'A', 'VCIT', null, null, 'VCIT', 'Vanguard Intermediate-Term Corp Bond ETF', 'Fixed Income', 'Domestic', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('73', 'A', 'A', 'VCMIX', null, null, 'VCMIX', 'Versus Capital Multi-Manager Real Estate Income Fund', 'Real Assets', 'Real Estate Income', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('74', 'A', 'A', 'VCSH', null, null, 'VCSH', 'Vanguard Short-Term Corporate Bond ETF', 'Fixed Income', 'Domestic', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('75', 'A', 'A', 'VEA', null, null, 'VEA', 'Vanguard FTSE Developed Markets ETF', 'International Equity', 'Large Blend', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('76', 'A', 'A', 'VRGIX', null, null, 'VRGIX', 'Stone Ridge Global Equity Variance Risk Prem. Fund', 'Alternatives', 'Equity & Variance Ri', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('77', 'A', 'A', 'VSS', null, null, 'VSS', 'Vanguard FTSE All-World ex-US Small Cap ETF', 'International Equity', 'Small/Mid Blend', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('78', 'A', 'A', 'VTI', null, null, 'VTI', 'Vanguard Total Stock Market ETF', 'Domestic Equity', 'Large Blend', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('79', 'A', 'A', 'VTV', null, null, 'VTV', 'Vanguard Value ETF', 'Domestic Equity', 'Large Value', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('80', 'A', 'A', 'VUG', null, null, 'VUG', 'Vanguard Growth ETF', 'Domestic Equity', 'Large Growth', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('81', 'A', 'A', 'VYM', null, null, 'VYM', 'Vanguard High Dividend Yield ETF', 'Domestic Equity', 'Large Value', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('82', 'A', 'A', 'XILSX', null, null, 'XILSX', 'Pioneer ILS Interval Fund', 'Alternatives', 'Reinsurance', null, null, '0', null, null, '0', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('83', 'A', 'A', 'IDA12', null, null, 'IDA12', 'FDIC INSURED DEPOSIT ACCOUNT IDA12 NOT COVERED BY SIPC', 'Money', 'Money', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('84', 'A', 'A', 'VFIDX', null, null, 'VFIDX', 'VANGUARD INTRM-TERM INVT GRADE ADMIRAL', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('85', 'A', 'A', 'VRIIX', null, null, 'VRIIX', 'STONE RIDGE INTL MASTERS VAR R ISK PREM I', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('86', 'A', 'A', 'VRPIX', null, null, 'VRPIX', 'STONE RIDGE US MASTER VAR RISK PERM CL I', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('90', 'A', 'A', 'AGAQX', null, null, 'AGAQX', '. 361 GLBL LNG/SHRT EQ INVT', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('91', 'A', 'A', 'IOFIX', null, null, 'IOFIX', 'CATALYST ALPHACENTRIC INCM OPP TYS I', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('93', 'A', 'A', 'EMRYX', null, null, 'EMRYX', 'VanEck Emerging Markets Fund', 'Emerging Markets Equity', 'Diversified Emrg. Mrkts.', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('94', 'A', 'A', 'VB', null, null, 'VB', 'Vanguard Small-Cap ETF', 'Domestic Equity', 'US Small Cap Blend', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('96', 'A', 'A', 'GBFAX', null, null, 'GBFAX', 'VAN ECK FDS EMERG MKTS FD CL A', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('97', 'A', 'A', 'MGCEX', null, null, 'MGCEX', 'MIRAE FUNDS ASIA GREAT CONSUME R A', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('99', 'A', 'A', 'LJMAX', null, null, 'LJMAX', 'TWO ROADS TR LJM PRESERVATION & GRWTH A', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('100', 'A', 'A', '2821.HK', null, null, '2821.HK', 'ABF Pan Asia Bond Index Fund', 'Fixed Income', 'Pan Asia Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('101', 'A', 'A', 'IPXJ.L', null, null, 'IPXJ.L', 'iShares MSCI Pacific ex Japan', 'Equity', 'Dev Asia X Japan Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('102', 'A', 'A', 'EIMI.L', null, null, 'EIMI.L', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('103', 'A', 'A', 'IHYG.L', null, null, 'IHYG.L', 'iShares Euro High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'E.U. High Yield Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('104', 'A', 'A', 'IHYU.L', null, null, 'IHYU.L', 'iShares $ High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'U.S. High Yield Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('105', 'A', 'A', 'SJPA.L', null, null, 'SJPA.L', 'iShares Core MSCI Japan IMI UCITS ETF', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('106', 'A', 'A', 'IMEU.L', null, null, 'IMEU.L', 'iShares MSCI Europe UCITS ETF (Dist)', 'Equity', 'Europe Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('107', 'A', 'A', 'IUAG.L', null, null, 'IUAG.L', 'iShares US Aggregate Bond UCITS ETF', 'Fixed Income', 'U.S. Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('111', 'A', 'A', 'EWS', null, null, 'EWS', 'iShares MSCI Singapore Capped', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('112', 'A', 'A', 'IEUR', null, null, 'IEUR', 'iShares MSCI Europe UCITS ETF (Dist)', 'Equity', 'Europe Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('113', 'A', 'A', 'EPP', null, null, 'EPP', 'iShares MSCI Pacific ex Japan', 'Equity', 'Dev Asia X Japan', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('114', 'A', 'A', 'EWJ', null, null, 'EWJ', 'ISHARES CORE MSCI JAP IMI UCITS', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('115', 'A', 'A', 'IEMG', null, null, 'IEMG', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('116', 'A', 'A', 'AGG', null, null, 'AGG', 'iShares US Aggregate Bond UCITS ETF', 'Fixed Income', 'U.S. Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('117', 'A', 'A', 'VUSD.L', null, null, 'VUSD.L', 'Vanguard S&P 500 UCITS ETF', 'Equity', 'U.S. Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('118', 'A', 'A', 'ES3.SI', null, null, 'ES3.SI', 'SPDR Straits Times Index ETF', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('119', 'A', 'A', 'KV4.SI', null, null, 'KV4.SI', 'Markit iBoxx ABF Singapore Government UCITS ETF 1C (KV4)', 'Fixed Income', 'Singapore Bonds', null, null, '0.2', null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('120', 'A', 'A', '2821.HK-SGD', null, null, '2821.HK-SGD', 'ABF Pan Asia Bond Index Fund', 'Fixed Income', 'Pan Asia Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('121', 'A', 'A', 'IPXJ-L-SGD', null, null, 'IPXJ-L-SGD', 'iShares MSCI Pacific ex Japan', 'Equity', 'Dev Asia X Japan Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('122', 'A', 'A', 'EIMI-L-SGD', null, null, 'EIMI-L-SGD', 'iShares Core MSCI Emerging Markets IMI', 'Equity', 'Emerging Mkt. Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('123', 'A', 'A', 'IHYG-L-SGD', null, null, 'IHYG-L-SGD', 'iShares Euro High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'E.U. High Yield Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('124', 'A', 'A', 'IHYU-L-SGD', null, null, 'IHYU-L-SGD', 'iShares $ High Yield Corporate Bond UCITS ETF', 'Fixed Income', 'U.S. High Yield Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('125', 'A', 'A', 'SJPA-L-SGD', null, null, 'SJPA-L-SGD', 'iShares Core MSCI Japan IMI UCITS ETF', 'Equity', 'Japan Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('126', 'A', 'A', 'IMEU-L-SGD', null, null, 'IMEU-L-SGD', 'iShares MSCI Europe UCITS ETF (Dist)', 'Equity', 'Europe Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('127', 'A', 'A', 'IUAG-L-SGD', null, null, 'IUAG-L-SGD', 'iShares US Aggregate Bond UCITS ETF', 'Fixed Income', 'U.S. Bonds', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('128', 'A', 'A', 'EWS-SGD', null, null, 'EWS-SGD', 'iShares MSCI Singapore Capped', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('129', 'A', 'A', 'VUSD-L-SGD', null, null, 'VUSD-L-SGD', 'Vanguard S&P 500 UCITS ETF', 'Equity', 'U.S. Equities', null, null, '0', null, null, '0', null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('130', 'A', 'A', 'ES3-SI-SGD', null, null, 'ES3-SI-SGD', 'SPDR Straits Times Index ETF', 'Equity', 'Singapore Equities', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('131', 'A', 'A', 'KV4-SI-SGD', null, null, 'KV4-SI-SGD', 'Markit iBoxx ABF Singapore Government UCITS ETF 1C (KV4)', 'Fixed Income', 'Singapore Bonds', null, null, '0.2', null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('132', 'A', 'A', 'GLD.N', null, null, 'GLD.N', 'SPDR® Gold Shares', 'Commodity', 'Precious Metals', null, null, '0.004', null, null, '0.134075', '', 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('133', 'A', 'A', 'IOFAX', null, null, 'IOFAX', 'CATALYST ALPHACENTRIC INCM OPP TYS A', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('134', 'A', 'A', 'LQTVX', null, null, 'LQTVX', '. LS THETA INVESTOR', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('135', 'A', 'A', 'RMPLX', null, null, 'RMPLX', 'RIVERNORTH MARKETPLACE LENDING CORP', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('136', 'A', 'A', 'IVE', null, null, 'IVE', 'ISHARES S&P 500 VALUE ETF', 'Equity', 'Equity', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('137', 'A', 'A', 'IWS', null, null, 'IWS', 'ISHARES RUSSELL MID-CAP VALUE ETF', 'Equity', 'Equity', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('138', 'A', 'A', 'SCHB', null, null, 'SCHB', 'SCHWAB US BROAD MARKET ETF', 'Equity', 'Equity', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('139', 'A', 'A', 'SCHF', null, null, 'SCHF', 'SCHWAB INTL EQUITY ETF', 'Equity', 'Equity', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('140', 'A', 'A', 'VBR', null, null, 'VBR', 'VANGUARD CRSP US SMALL CAP VAL UE IND ET', 'Equity', 'Equity', null, null, null, null, null, null, null, 'SGX', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('141', 'A', 'A', 'C.N', null, null, 'C.N', 'Citigroup Inc.', 'Equity', 'Equity', null, null, null, null, null, null, null, 'NYSE', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('142', 'A', 'A', 'IBM.N', null, null, 'IBM.N', 'International Business Machines Corporation', 'Equity', 'Equity', null, null, null, null, null, null, null, 'NYSE', 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('143', 'A', 'A', 'MRK.N', null, null, null, 'Merck & Co., Inc.', 'Equity', 'Large Cap', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('144', 'A', 'A', 'UL.N', null, null, null, 'Unilever PLC', 'Equity', 'Large Cap', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('145', 'A', 'A', 'DAL.N', null, null, null, 'Delta Air Lines, Inc. ', 'Equity', 'Large Cap', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('146', 'A', 'A', 'TOL.N', null, null, null, 'Toll Brothers, Inc.', 'Equity', 'Large Cap', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('147', 'A', 'A', 'AFICX', null, null, null, 'AMERICAN FUNDS FUNDAMENTAL INV ESTORS C', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('148', 'A', 'A', 'CWBCX', null, null, null, 'AMERICAN FUNDS CAPITAL WORLD B OND C', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('149', 'A', 'A', 'CWGCX', null, null, null, 'AMERICAN FUNDS CAPITAL WORLD G RWTH & INCOME C', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('150', 'A', 'A', 'GFACX', null, null, null, 'AMERICAN FUNDS GROWTH FUND OF AMERICA C', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, null, 'USD');
INSERT INTO `invdb`.`sec_master` (`instrumentid`, `status`, `securityStatus`, `ticker`, `cusip`, `isin`, `ric`, `name`, `assetclass`, `subclass`, `type`, `style`, `expenseRatio`, `inception`, `issuer`, `securityRiskSTD`, `rbsaFlag`, `exchange`, `base_currency`) VALUES ('151', 'A', 'A', 'SCWCX', null, null, null, 'AMERICAN FUNDS SMALLCAP WORLD C', 'Mutual fund', 'Mutual fund', null, null, null, null, null, null, null, null, 'USD');


 
