## Insertion script for dc_template_details mode=UAT & product=TCM

delete from `service`.`dc_template_details` where mode='UAT' and product='TCM' and service='DOCUSIGN-SERVICES';

INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK', 'd71203fe-3987-4592-a270-12c8ba7987b5', 'AdvisorDirect Disclosure Brochure, Rev. April', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'ADV_DIRECT_DISC_BOOK2', 'd71203fe-3987-4592-a270-12c8ba7987b5', 'AdvisorDirect Disclosure Brochure, Rev. April', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_ACAT_OTHER', 'ca47568b-70d6-42c4-b10f-0e10545e1a31', 'Account Transfer Form Other', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_ACCT_ADV', 'c3818a4d-320f-4a6c-8181-5c0f45206d69', 'Account ADV Forms', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_ACCT_APPLI', 'e21c6a62-8527-40d8-a006-26845ca2a1d5', 'Account Application', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_ACCT_TRANS', 'de101955-89c5-4cad-99b8-ec04fda60790', 'Account Transfer Form', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_CHNG_ADDRS', 'bba60794-5788-4656-8bb7-5857a228a52a', 'Change Address', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_ELECT_FUND_TRANS', '7c19f254-3616-402e-ac0b-3279a241153b', 'Electronic Funds Transfer Form', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_IRAQRP_BENE', '0752806c-994e-4a48-b709-58ae78973882', 'IRA/QRP Beneficiary Account App', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_IRA_APPLI', 'ff8ec806-45e4-499d-846d-4ad84e628295', 'IRA Application', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_LPOA', '314a6465-44c1-4460-a31a-c10cc92ae886', 'LPOA', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_MOVE_MONEY', 'c607c4a9-09ee-4aea-8aff-e9e74d7a43e6', 'Move Money', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_MOVE_MONEY_IRA', 'a8e87128-8c05-4080-8fb9-c842709eada8', 'Move Money IRA', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_TCM_ADV_2AB', 'f5fd0a0d-1fca-486e-9de8-92386f322201', 'TCM ADV 2AB', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_TCM_ADV_AGREE', 'c0d642a7-7e19-486a-9b64-4e3d724f9965', 'Building Benjamins Tradition Advisory Agreeme', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'BB_TCM_PRIVACY_NOTICE', 'ce93131f-68f2-4cf7-80e0-51a0636de5f2', 'TCM Privacy Notice', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'GENE_EMAIL_MESSAGE', '6fe4789b-f36d-4c05-a974-67037c5a692e', 'Generic Email Message', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'IRA_CUST_AGREE', '961c2b94-f14f-477e-a398-30775a06d81d', 'IRA Custodial Account Agreement- Mandatory fo', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'IRA_DIST_HOLD_FORM', 'ab0b4ead-b0e1-419c-ad96-131d8b134f2e', 'IRA Dist/WH Form', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'MARGIN_AGREE', 'd72c0183-fced-4bf2-84cd-2ff0b20f6c20', 'Margin Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'PRIM_BROK_AGREE', '01eb749a-709c-4dc8-b07f-22c0c73b2af8', 'Prime Brokerage Services Agreement Amendment', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAE_ACAT_OTHER', 'c62d9775-24f8-46c4-91fe-834ce0dda1f6', 'TCM External Manual Account Transfer', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAE_ADV_2AB', '09123936-8876-4263-aa1b-d741654e9505', 'TCM ADV 2AB', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAE_ADV_AGREE', 'd5a1c41b-21ce-4c99-9c8b-4c9ad403320a', 'Tradition Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAE_PRIVACY_NOTICE', '7efde06a-1180-4001-a0d6-c995440d7a17', 'TCM Privacy Notice', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAI_ACAT_OTHER', '542ad322-7aa0-4c45-9f97-6187b198b874', 'TCM Internal Manual Account Transfer', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAI_ADV_2AB', '01ee8896-5340-460c-87d8-b95fe9cf1b0d', 'TCM ADV 2AB', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAI_ADV_AGREE', 'c31f1730-84be-4ee5-bf6d-318b200d7e14', 'Tradition Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TAI_PRIVACY_NOTICE', 'aa56763c-5fba-43c0-85cd-eabc75b0eeeb', 'TCM Privacy Notice', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TCM_DIRECT_AGREE', 'de7b162e-7cb9-4a02-ad82-400758521d14', 'TCM - TDAD Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TCM_THIRED_PARTY_DISC', '1111', 'TEMPLATE NAME', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TD_ADV_DIRECT_AGREE', 'c6360f7e-3804-40e1-96ac-1cb2a62d536c', 'TCM - TDAD Advisory Agreement', 'Y', 'A');
INSERT INTO `service`.`dc_template_details` (`mode`, `company`, `service`, `tempCode`, `tempId`, `tempName`, `authRequired`, `status`) VALUES ('UAT', 'TCM', 'DOCUSIGN-SERVICES', 'TD_DISC_PACK', 'fc2be0bc-f6aa-44a8-9f92-fb760b0907fb', 'TD Ameritrade Institutional Disclosure Packet', 'Y', 'A');
