UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='GLD.N' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Commodity' and`ticker`='GLD-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='EIMI.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='EIMI-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='ES3.SI' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='ES3-SI-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IMEU.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='IMEU-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IPXJ.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='IPXJ-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='SJPA.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='SJPA-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='VUSD.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='VUSD-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='2821.HK' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='2821.HK-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYG.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IHYG-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYU.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IHYU-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IUAG.L' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IUAG-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='KV4.SI' WHERE `theme`='0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='KV4-SI-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='GLD.N' WHERE `theme`='T.0.SGWealth' and`assetclass`='Commodity' and`ticker`='GLD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='EIMI.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='EIMI-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='ES3.SI' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='ES3-SI';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IMEU.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='IMEU-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IPXJ.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='IPXJ-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='SJPA.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='SJPA-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='VUSD.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Equity' and`ticker`='VUSD-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='GLD.N' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Commodity' and`ticker`='GLD-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='Cash' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Cash' and`ticker`='Cash-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='EIMI.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='EIMI-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='ES3.SI' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='ES3-SI-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IMEU.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='IMEU-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IPXJ.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='IPXJ-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='SJPA.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='SJPA-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='VUSD.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Equity' and`ticker`='VUSD-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='2821.HK' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='2821.HK-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYG.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IHYG-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYU.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IHYU-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IUAG.L' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='IUAG-L-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='KV4.SI' WHERE `theme`='T.0.SGWealthSGD' and`assetclass`='Fixed Income' and`ticker`='KV4-SI-SGD';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYG.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Fixed Income' and`ticker`='IHYG-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IHYU.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Fixed Income' and`ticker`='IHYU-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='IUAG.L' WHERE `theme`='T.0.SGWealth' and`assetclass`='Fixed Income' and`ticker`='IUAG-L';
UPDATE `invdb`.`sec_prime_asset_group` SET `ticker`='KV4.SI' WHERE `theme`='T.0.SGWealth' and`assetclass`='Fixed Income' and`ticker`='KV4-SI';
